In [2]:
!pip install sqlalchemy
!pip install pandas
!pip install mysql-connector-python

Requirement already satisfied: sqlalchemy in c:\users\paster\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\paster\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\paster\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: pandas in c:\users\paster\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\paster\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\paster\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\paster\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\paster\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\paster\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: mysql-connector-python in c:\users\paster\anaconda3\lib\site-packages (9.3.0)

In [3]:
import os
import dotenv
import sqlalchemy
import pandas as pd

In [4]:
#Importiamo il database Nati per Regione
df = pd.read_csv(r'C:\Users\paster\Downloads\Nascite.csv')
df

,Regione,1999,2000,2001,2002,2003,2004,2005,2006,2007,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Note
0,Piemonte,34639,35874,34857,35716,36370,37413,37251,37851,38565,...,32908,31732,30830,29072,27972,27107,26700,25975,25077,NaN
1,Valle d'Aosta/Vallée d'Aoste,1103,1171,1112,1107,1151,1177,1161,1250,1241,...,987,962,906,904,841,776,744,781,718,NaN
2,Liguria,10998,11325,11368,11492,11536,12014,11957,12146,12156,...,10155,9901,9571,9043,8747,8752,8556,8479,8343,NaN
3,Lombardia,82285,85250,85075,86633,87559,92898,92480,95156,96280,...,84149,81588,78888,75693,73117,69235,68918,67482,65659,NaN
4,Trentino-Alto Adige/Südtirol,10594,10562,10424,10275,10345,10902,10719,10602,10680,...,10173,10089,9846,9637,9473,9239,9363,8923,8484,NaN
5,Provincia Autonoma di Bolzano,5592,5426,5469,5208,5388,5450,5525,5409,5502,...,5337,5447,5351,5284,5234,5191,5173,4912,4695,NaN
6,Provincia Autonoma di Trento,5002,5136,4955,5067,4957,5452,5194,5193,5178,...,4836,4642,4495,4353,4239,4048,4190,4011,3789,NaN
7,Veneto,41720,43299,42204,43420,43898,47084,46254,47047,47621,...,38952,37851,36587,35393,33556,32672,32799,31754,30438,NaN
8,Friuli-Venezia Giulia,9100,9576,9545,9586,9864,10114,10093,10363,10569,...,8584,8492,8132,7829,7495,7434,7269,7277,6982,NaN
9,Emilia-Romagna,31857,33996,34275,35674,35926,38222,38653,39595,40680,...,35813,34578,33011,32400,30922,29861,29836,29615,28568,NaN
10,Toscana,27093,28386,28385,29384,29000,31695,31390,31595,32258,...,27494,26916,26092,24863,23451,22380,22592,21610,20875,NaN
11,Umbria,6612,6786,6761,7099,7115,7617,7732,7822,8028,...,6542,6353,6116,5792,5577,5268,5238,4926,4766,NaN
12,Marche,12190,12449,12122,12610,12745,13249,13305,13597,13902,...,11904,11482,10669,10171,9667,9432,9222,8788,8797,NaN
13,Lazio,50658,48884,47761,48497,50490,52032,50833,52913,52445,...,48231,47595,44573,42150,38885,37982,37237,36062,34292,NaN
14,Abruzzo,10768,10882,10867,10580,10971,11101,11200,11087,11428,...,10238,10074,9521,8937,8500,8237,8290,8023,7578,NaN
15,Molise,2776,2671,2567,2600,2611,2549,2527,2461,2507,...,2181,2088,2120,1895,1927,1713,1685,1683,1661,NaN
16,Campania,68669,67181,66587,65068,65194,65102,62599,62279,61800,...,51005,50384,49949,48066,46731,45078,43403,44469,42925,NaN
17,Puglia,42444,42647,41837,40145,39744,40569,38715,37764,38224,...,31577,31132,30033,28921,27586,26455,26381,26301,25591,NaN
18,Basilicata,5645,5662,5439,5472,5265,5297,4908,4958,4873,...,4122,4017,4007,3717,3672,3523,3330,3221,3123,NaN
19,Calabria,19612,19421,18774,18451,18809,18712,18228,18328,18107,...,16376,16036,15679,15177,14491,13966,13219,13451,13282,NaN
20,Sicilia,54879,53152,51890,51234,51899,51728,50791,49940,49186,...,43307,41641,41479,40649,38616,37520,37235,36810,35489,NaN
21,Sardegna,13600,13865,13432,13155,13571,13124,13226,13256,13383,...,11082,10527,10142,9438,8858,8262,8232,7703,7242,NaN
22,Italia,537242,543039,535282,538198,544063,562599,554022,560010,563933,...,485780,473438,458151,439747,420084,404892,400249,393333,379890,NaN

In [5]:
import pandas as pd

# df è il tuo DataFrame importato
df.info()          # tipi di dato e valori non nulli per colonna
df.head()           # prime righe
df.describe(include='all') # statistiche sommario (per numeriche e non)
df.isna().sum()      # quanti NA per colonna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 27 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Regione  23 non-null     object
 1   1999     23 non-null     int64
 2   2000     23 non-null     int64
 3   2001     23 non-null     int64
 4   2002     23 non-null     int64
 5   2003     23 non-null     int64
 6   2004     23 non-null     int64
 7   2005     23 non-null     int64
 8   2006     23 non-null     int64
 9   2007     23 non-null     int64
 10  2008     23 non-null     int64
 11  2009     23 non-null     int64
 12  2010     23 non-null     int64
 13  2011     23 non-null     int64
 14  2012     23 non-null     int64
 15  2013     23 non-null     int64
 16  2014     23 non-null     int64
 17  2015     23 non-null     int64
 18  2016     23 non-null     int64
 19  2017     23 non-null     int64
 20  2018     23 non-null     int64
 21  2019     23 non-null     int64
 22  2020     23 non-null     int64
 23  2021     23 non-null     int64
 24  2022     23 non-null     int64
 25  2023     23 non-null     int64
 26  Note     0 non-null      float64
dtypes: float64(1), int64(25), object(1)
memory usage: 5.0+ KB

Regione     0
1999        0
2000        0
2001        0
2002        0
2003        0
2004        0
2005        0
2006        0
2007        0
2008        0
2009        0
2010        0
2011        0
2012        0
2013        0
2014        0
2015        0
2016        0
2017        0
2018        0
2019        0
2020        0
2021        0
2022        0
2023        0
Note       23
dtype: int64

In [6]:
# Elimina colonne specifiche
cols_to_drop = ['Note']
df = df.drop(columns=cols_to_drop, errors='ignore') 
df

,Regione,1999,2000,2001,2002,2003,2004,2005,2006,2007,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Piemonte,34639,35874,34857,35716,36370,37413,37251,37851,38565,...,34637,32908,31732,30830,29072,27972,27107,26700,25975,25077
1,Valle d'Aosta/Vallée d'Aoste,1103,1171,1112,1107,1151,1177,1161,1250,1241,...,1119,987,962,906,904,841,776,744,781,718
2,Liguria,10998,11325,11368,11492,11536,12014,11957,12146,12156,...,10749,10155,9901,9571,9043,8747,8752,8556,8479,8343
3,Lombardia,82285,85250,85075,86633,87559,92898,92480,95156,96280,...,86239,84149,81588,78888,75693,73117,69235,68918,67482,65659
4,Trentino-Alto Adige/Südtirol,10594,10562,10424,10275,10345,10902,10719,10602,10680,...,10379,10173,10089,9846,9637,9473,9239,9363,8923,8484
5,Provincia Autonoma di Bolzano,5592,5426,5469,5208,5388,5450,5525,5409,5502,...,5517,5337,5447,5351,5284,5234,5191,5173,4912,4695
6,Provincia Autonoma di Trento,5002,5136,4955,5067,4957,5452,5194,5193,5178,...,4862,4836,4642,4495,4353,4239,4048,4190,4011,3789
7,Veneto,41720,43299,42204,43420,43898,47084,46254,47047,47621,...,40619,38952,37851,36587,35393,33556,32672,32799,31754,30438
8,Friuli-Venezia Giulia,9100,9576,9545,9586,9864,10114,10093,10363,10569,...,9187,8584,8492,8132,7829,7495,7434,7269,7277,6982
9,Emilia-Romagna,31857,33996,34275,35674,35926,38222,38653,39595,40680,...,36668,35813,34578,33011,32400,30922,29861,29836,29615,28568
10,Toscana,27093,28386,28385,29384,29000,31695,31390,31595,32258,...,29118,27494,26916,26092,24863,23451,22380,22592,21610,20875
11,Umbria,6612,6786,6761,7099,7115,7617,7732,7822,8028,...,7015,6542,6353,6116,5792,5577,5268,5238,4926,4766
12,Marche,12190,12449,12122,12610,12745,13249,13305,13597,13902,...,12363,11904,11482,10669,10171,9667,9432,9222,8788,8797
13,Lazio,50658,48884,47761,48497,50490,52032,50833,52913,52445,...,50360,48231,47595,44573,42150,38885,37982,37237,36062,34292
14,Abruzzo,10768,10882,10867,10580,10971,11101,11200,11087,11428,...,10534,10238,10074,9521,8937,8500,8237,8290,8023,7578
15,Molise,2776,2671,2567,2600,2611,2549,2527,2461,2507,...,2213,2181,2088,2120,1895,1927,1713,1685,1683,1661
16,Campania,68669,67181,66587,65068,65194,65102,62599,62279,61800,...,51243,51005,50384,49949,48066,46731,45078,43403,44469,42925
17,Puglia,42444,42647,41837,40145,39744,40569,38715,37764,38224,...,33191,31577,31132,30033,28921,27586,26455,26381,26301,25591
18,Basilicata,5645,5662,5439,5472,5265,5297,4908,4958,4873,...,4123,4122,4017,4007,3717,3672,3523,3330,3221,3123
19,Calabria,19612,19421,18774,18451,18809,18712,18228,18328,18107,...,16490,16376,16036,15679,15177,14491,13966,13219,13451,13282
20,Sicilia,54879,53152,51890,51234,51899,51728,50791,49940,49186,...,44876,43307,41641,41479,40649,38616,37520,37235,36810,35489
21,Sardegna,13600,13865,13432,13155,13571,13124,13226,13256,13383,...,11473,11082,10527,10142,9438,8858,8262,8232,7703,7242
22,Italia,537242,543039,535282,538198,544063,562599,554022,560010,563933,...,502596,485780,473438,458151,439747,420084,404892,400249,393333,379890

In [7]:
# Gestisci NaN 
df = df.dropna(subset=['Regione'])
df

,Regione,1999,2000,2001,2002,2003,2004,2005,2006,2007,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Piemonte,34639,35874,34857,35716,36370,37413,37251,37851,38565,...,34637,32908,31732,30830,29072,27972,27107,26700,25975,25077
1,Valle d'Aosta/Vallée d'Aoste,1103,1171,1112,1107,1151,1177,1161,1250,1241,...,1119,987,962,906,904,841,776,744,781,718
2,Liguria,10998,11325,11368,11492,11536,12014,11957,12146,12156,...,10749,10155,9901,9571,9043,8747,8752,8556,8479,8343
3,Lombardia,82285,85250,85075,86633,87559,92898,92480,95156,96280,...,86239,84149,81588,78888,75693,73117,69235,68918,67482,65659
4,Trentino-Alto Adige/Südtirol,10594,10562,10424,10275,10345,10902,10719,10602,10680,...,10379,10173,10089,9846,9637,9473,9239,9363,8923,8484
5,Provincia Autonoma di Bolzano,5592,5426,5469,5208,5388,5450,5525,5409,5502,...,5517,5337,5447,5351,5284,5234,5191,5173,4912,4695
6,Provincia Autonoma di Trento,5002,5136,4955,5067,4957,5452,5194,5193,5178,...,4862,4836,4642,4495,4353,4239,4048,4190,4011,3789
7,Veneto,41720,43299,42204,43420,43898,47084,46254,47047,47621,...,40619,38952,37851,36587,35393,33556,32672,32799,31754,30438
8,Friuli-Venezia Giulia,9100,9576,9545,9586,9864,10114,10093,10363,10569,...,9187,8584,8492,8132,7829,7495,7434,7269,7277,6982
9,Emilia-Romagna,31857,33996,34275,35674,35926,38222,38653,39595,40680,...,36668,35813,34578,33011,32400,30922,29861,29836,29615,28568
10,Toscana,27093,28386,28385,29384,29000,31695,31390,31595,32258,...,29118,27494,26916,26092,24863,23451,22380,22592,21610,20875
11,Umbria,6612,6786,6761,7099,7115,7617,7732,7822,8028,...,7015,6542,6353,6116,5792,5577,5268,5238,4926,4766
12,Marche,12190,12449,12122,12610,12745,13249,13305,13597,13902,...,12363,11904,11482,10669,10171,9667,9432,9222,8788,8797
13,Lazio,50658,48884,47761,48497,50490,52032,50833,52913,52445,...,50360,48231,47595,44573,42150,38885,37982,37237,36062,34292
14,Abruzzo,10768,10882,10867,10580,10971,11101,11200,11087,11428,...,10534,10238,10074,9521,8937,8500,8237,8290,8023,7578
15,Molise,2776,2671,2567,2600,2611,2549,2527,2461,2507,...,2213,2181,2088,2120,1895,1927,1713,1685,1683,1661
16,Campania,68669,67181,66587,65068,65194,65102,62599,62279,61800,...,51243,51005,50384,49949,48066,46731,45078,43403,44469,42925
17,Puglia,42444,42647,41837,40145,39744,40569,38715,37764,38224,...,33191,31577,31132,30033,28921,27586,26455,26381,26301,25591
18,Basilicata,5645,5662,5439,5472,5265,5297,4908,4958,4873,...,4123,4122,4017,4007,3717,3672,3523,3330,3221,3123
19,Calabria,19612,19421,18774,18451,18809,18712,18228,18328,18107,...,16490,16376,16036,15679,15177,14491,13966,13219,13451,13282
20,Sicilia,54879,53152,51890,51234,51899,51728,50791,49940,49186,...,44876,43307,41641,41479,40649,38616,37520,37235,36810,35489
21,Sardegna,13600,13865,13432,13155,13571,13124,13226,13256,13383,...,11473,11082,10527,10142,9438,8858,8262,8232,7703,7242
22,Italia,537242,543039,535282,538198,544063,562599,554022,560010,563933,...,502596,485780,473438,458151,439747,420084,404892,400249,393333,379890

In [8]:
# Esporto in CSV
df.to_csv('dati_puliti.csv', index=False, encoding='utf-8', na_rep=None)

In [9]:
#Importiamo il database Nati per cittadinanza dei genitori ed età della madre 2020
madre_2020 = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (3).csv')
madre_2020

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale,Note
0,Piemonte,2020,0,120,858,3835,7308,5450,1693,159,18,19441,NaN
1,Valle d'Aosta/Vallée d'Aoste,2020,0,2,32,146,216,160,52,8,0,616,NaN
2,Liguria,2020,0,24,264,1128,2223,1724,551,90,7,6011,NaN
3,Lombardia,2020,0,254,1881,8320,17696,14544,4350,417,51,47513,NaN
4,Trentino-Alto Adige/Südtirol,2020,2,43,363,1629,2635,1742,456,43,3,6916,NaN
5,Provincia Autonoma di Bolzano,2020,2,27,251,960,1492,936,225,22,2,3917,NaN
6,Provincia Autonoma di Trento,2020,0,16,112,669,1143,806,231,21,1,2999,NaN
7,Veneto,2020,0,126,924,4157,8764,6776,1924,228,21,22920,NaN
8,Friuli-Venezia Giulia,2020,0,30,215,1015,2050,1510,493,52,7,5372,NaN
9,Emilia-Romagna,2020,0,99,817,3562,7207,5980,1936,220,30,19851,NaN
10,Toscana,2020,0,69,567,2671,5790,5022,1754,210,22,16105,NaN
11,Umbria,2020,0,23,171,685,1398,1171,352,34,5,3839,NaN
12,Marche,2020,0,33,280,1226,2596,2261,719,76,9,7200,NaN
13,Lazio,2020,0,193,1405,5055,9973,9104,3235,434,72,29471,NaN
14,Abruzzo,2020,0,55,367,1285,2390,2041,606,85,8,6837,NaN
15,Molise,2020,0,10,84,283,510,443,152,11,1,1494,NaN
16,Campania,2020,0,689,3627,9914,14726,9623,2483,265,42,41369,NaN
17,Puglia,2020,1,384,1827,5131,8411,6244,1859,224,16,24097,NaN
18,Basilicata,2020,0,25,138,600,1104,942,292,39,8,3148,NaN
19,Calabria,2020,0,121,945,2879,4471,3072,916,103,12,12519,NaN
20,Sicilia,2020,0,841,3327,8341,11591,7855,2093,220,35,34303,NaN
21,Sardegna,2020,0,60,456,1288,2405,2335,862,108,11,7525,NaN
22,Italia,2020,3,3201,18548,63150,113464,87999,26778,3026,378,316547,NaN

In [10]:
# Elimina colonne specifiche
cols_to_drop = ['Note']
madre_2020 = madre_2020.drop(columns=cols_to_drop, errors='ignore') 
madre_2020

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2020,0,120,858,3835,7308,5450,1693,159,18,19441
1,Valle d'Aosta/Vallée d'Aoste,2020,0,2,32,146,216,160,52,8,0,616
2,Liguria,2020,0,24,264,1128,2223,1724,551,90,7,6011
3,Lombardia,2020,0,254,1881,8320,17696,14544,4350,417,51,47513
4,Trentino-Alto Adige/Südtirol,2020,2,43,363,1629,2635,1742,456,43,3,6916
5,Provincia Autonoma di Bolzano,2020,2,27,251,960,1492,936,225,22,2,3917
6,Provincia Autonoma di Trento,2020,0,16,112,669,1143,806,231,21,1,2999
7,Veneto,2020,0,126,924,4157,8764,6776,1924,228,21,22920
8,Friuli-Venezia Giulia,2020,0,30,215,1015,2050,1510,493,52,7,5372
9,Emilia-Romagna,2020,0,99,817,3562,7207,5980,1936,220,30,19851
10,Toscana,2020,0,69,567,2671,5790,5022,1754,210,22,16105
11,Umbria,2020,0,23,171,685,1398,1171,352,34,5,3839
12,Marche,2020,0,33,280,1226,2596,2261,719,76,9,7200
13,Lazio,2020,0,193,1405,5055,9973,9104,3235,434,72,29471
14,Abruzzo,2020,0,55,367,1285,2390,2041,606,85,8,6837
15,Molise,2020,0,10,84,283,510,443,152,11,1,1494
16,Campania,2020,0,689,3627,9914,14726,9623,2483,265,42,41369
17,Puglia,2020,1,384,1827,5131,8411,6244,1859,224,16,24097
18,Basilicata,2020,0,25,138,600,1104,942,292,39,8,3148
19,Calabria,2020,0,121,945,2879,4471,3072,916,103,12,12519
20,Sicilia,2020,0,841,3327,8341,11591,7855,2093,220,35,34303
21,Sardegna,2020,0,60,456,1288,2405,2335,862,108,11,7525
22,Italia,2020,3,3201,18548,63150,113464,87999,26778,3026,378,316547

In [11]:
# Gestisci NaN 
madre_2020 = madre_2020.dropna()
madre_2020

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2020,0,120,858,3835,7308,5450,1693,159,18,19441
1,Valle d'Aosta/Vallée d'Aoste,2020,0,2,32,146,216,160,52,8,0,616
2,Liguria,2020,0,24,264,1128,2223,1724,551,90,7,6011
3,Lombardia,2020,0,254,1881,8320,17696,14544,4350,417,51,47513
4,Trentino-Alto Adige/Südtirol,2020,2,43,363,1629,2635,1742,456,43,3,6916
5,Provincia Autonoma di Bolzano,2020,2,27,251,960,1492,936,225,22,2,3917
6,Provincia Autonoma di Trento,2020,0,16,112,669,1143,806,231,21,1,2999
7,Veneto,2020,0,126,924,4157,8764,6776,1924,228,21,22920
8,Friuli-Venezia Giulia,2020,0,30,215,1015,2050,1510,493,52,7,5372
9,Emilia-Romagna,2020,0,99,817,3562,7207,5980,1936,220,30,19851
10,Toscana,2020,0,69,567,2671,5790,5022,1754,210,22,16105
11,Umbria,2020,0,23,171,685,1398,1171,352,34,5,3839
12,Marche,2020,0,33,280,1226,2596,2261,719,76,9,7200
13,Lazio,2020,0,193,1405,5055,9973,9104,3235,434,72,29471
14,Abruzzo,2020,0,55,367,1285,2390,2041,606,85,8,6837
15,Molise,2020,0,10,84,283,510,443,152,11,1,1494
16,Campania,2020,0,689,3627,9914,14726,9623,2483,265,42,41369
17,Puglia,2020,1,384,1827,5131,8411,6244,1859,224,16,24097
18,Basilicata,2020,0,25,138,600,1104,942,292,39,8,3148
19,Calabria,2020,0,121,945,2879,4471,3072,916,103,12,12519
20,Sicilia,2020,0,841,3327,8341,11591,7855,2093,220,35,34303
21,Sardegna,2020,0,60,456,1288,2405,2335,862,108,11,7525
22,Italia,2020,3,3201,18548,63150,113464,87999,26778,3026,378,316547

In [12]:
#Cambio il formato data
madre_2020['Anno'] = pd.to_datetime(madre_2020['Anno'], format='%Y')
madre_2020

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2020-01-01,0,120,858,3835,7308,5450,1693,159,18,19441
1,Valle d'Aosta/Vallée d'Aoste,2020-01-01,0,2,32,146,216,160,52,8,0,616
2,Liguria,2020-01-01,0,24,264,1128,2223,1724,551,90,7,6011
3,Lombardia,2020-01-01,0,254,1881,8320,17696,14544,4350,417,51,47513
4,Trentino-Alto Adige/Südtirol,2020-01-01,2,43,363,1629,2635,1742,456,43,3,6916
5,Provincia Autonoma di Bolzano,2020-01-01,2,27,251,960,1492,936,225,22,2,3917
6,Provincia Autonoma di Trento,2020-01-01,0,16,112,669,1143,806,231,21,1,2999
7,Veneto,2020-01-01,0,126,924,4157,8764,6776,1924,228,21,22920
8,Friuli-Venezia Giulia,2020-01-01,0,30,215,1015,2050,1510,493,52,7,5372
9,Emilia-Romagna,2020-01-01,0,99,817,3562,7207,5980,1936,220,30,19851
10,Toscana,2020-01-01,0,69,567,2671,5790,5022,1754,210,22,16105
11,Umbria,2020-01-01,0,23,171,685,1398,1171,352,34,5,3839
12,Marche,2020-01-01,0,33,280,1226,2596,2261,719,76,9,7200
13,Lazio,2020-01-01,0,193,1405,5055,9973,9104,3235,434,72,29471
14,Abruzzo,2020-01-01,0,55,367,1285,2390,2041,606,85,8,6837
15,Molise,2020-01-01,0,10,84,283,510,443,152,11,1,1494
16,Campania,2020-01-01,0,689,3627,9914,14726,9623,2483,265,42,41369
17,Puglia,2020-01-01,1,384,1827,5131,8411,6244,1859,224,16,24097
18,Basilicata,2020-01-01,0,25,138,600,1104,942,292,39,8,3148
19,Calabria,2020-01-01,0,121,945,2879,4471,3072,916,103,12,12519
20,Sicilia,2020-01-01,0,841,3327,8341,11591,7855,2093,220,35,34303
21,Sardegna,2020-01-01,0,60,456,1288,2405,2335,862,108,11,7525
22,Italia,2020-01-01,3,3201,18548,63150,113464,87999,26778,3026,378,316547

In [13]:
# Esporto in CSV
madre_2020.to_csv('madre_2020.csv', index=False, encoding='utf-8', na_rep=None)

In [14]:
#Importiamo il database Nati per cittadinanza dei genitori ed età della madre 2021
madre_2021 = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (4).csv')
madre_2021

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale,Note
0,Piemonte,2021,1,97,820,3813,7268,5629,1516,176,25,19345,NaN
1,Valle d'Aosta/Vallée d'Aoste,2021,0,2,31,141,221,150,33,1,0,579,NaN
2,Liguria,2021,0,31,199,1059,2288,1703,538,63,8,5889,NaN
3,Lombardia,2021,0,249,1619,7839,18424,15006,4124,383,42,47686,NaN
4,Trentino-Alto Adige/Südtirol,2021,0,33,390,1660,2702,1760,468,35,3,7051,NaN
5,Provincia Autonoma di Bolzano,2021,0,25,251,975,1479,903,237,19,2,3891,NaN
6,Provincia Autonoma di Trento,2021,0,8,139,685,1223,857,231,16,1,3160,NaN
7,Veneto,2021,0,99,816,4165,8951,6936,2060,184,20,23231,NaN
8,Friuli-Venezia Giulia,2021,0,17,227,976,1977,1534,447,53,3,5234,NaN
9,Emilia-Romagna,2021,0,87,736,3416,7475,6005,1773,211,38,19741,NaN
10,Toscana,2021,0,71,534,2540,5944,5341,1653,174,21,16278,NaN
11,Umbria,2021,0,13,161,696,1370,1178,374,35,7,3834,NaN
12,Marche,2021,0,32,276,1199,2630,2206,656,52,5,7056,NaN
13,Lazio,2021,0,163,1303,4794,10170,9480,3058,404,68,29440,NaN
14,Abruzzo,2021,0,53,355,1262,2379,2128,658,61,14,6910,NaN
15,Molise,2021,0,16,92,279,493,465,134,11,1,1491,NaN
16,Campania,2021,1,623,3451,8875,14192,9965,2686,263,45,40101,NaN
17,Puglia,2021,1,334,1965,4649,8586,6477,1909,189,12,24122,NaN
18,Basilicata,2021,0,21,134,521,1089,903,269,35,3,2975,NaN
19,Calabria,2021,1,106,776,2724,4218,3066,872,77,11,11851,NaN
20,Sicilia,2021,0,864,3361,7729,11538,8177,2124,197,26,34016,NaN
21,Sardegna,2021,1,64,392,1292,2417,2394,871,96,14,7541,NaN
22,Italia,2021,5,2975,17638,59629,114332,90503,26223,2700,366,314371,NaN

In [15]:
#Cambio il formato data
madre_2021['Anno'] = pd.to_datetime(madre_2021['Anno'], format='%Y')
madre_2021

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale,Note
0,Piemonte,2021-01-01,1,97,820,3813,7268,5629,1516,176,25,19345,NaN
1,Valle d'Aosta/Vallée d'Aoste,2021-01-01,0,2,31,141,221,150,33,1,0,579,NaN
2,Liguria,2021-01-01,0,31,199,1059,2288,1703,538,63,8,5889,NaN
3,Lombardia,2021-01-01,0,249,1619,7839,18424,15006,4124,383,42,47686,NaN
4,Trentino-Alto Adige/Südtirol,2021-01-01,0,33,390,1660,2702,1760,468,35,3,7051,NaN
5,Provincia Autonoma di Bolzano,2021-01-01,0,25,251,975,1479,903,237,19,2,3891,NaN
6,Provincia Autonoma di Trento,2021-01-01,0,8,139,685,1223,857,231,16,1,3160,NaN
7,Veneto,2021-01-01,0,99,816,4165,8951,6936,2060,184,20,23231,NaN
8,Friuli-Venezia Giulia,2021-01-01,0,17,227,976,1977,1534,447,53,3,5234,NaN
9,Emilia-Romagna,2021-01-01,0,87,736,3416,7475,6005,1773,211,38,19741,NaN
10,Toscana,2021-01-01,0,71,534,2540,5944,5341,1653,174,21,16278,NaN
11,Umbria,2021-01-01,0,13,161,696,1370,1178,374,35,7,3834,NaN
12,Marche,2021-01-01,0,32,276,1199,2630,2206,656,52,5,7056,NaN
13,Lazio,2021-01-01,0,163,1303,4794,10170,9480,3058,404,68,29440,NaN
14,Abruzzo,2021-01-01,0,53,355,1262,2379,2128,658,61,14,6910,NaN
15,Molise,2021-01-01,0,16,92,279,493,465,134,11,1,1491,NaN
16,Campania,2021-01-01,1,623,3451,8875,14192,9965,2686,263,45,40101,NaN
17,Puglia,2021-01-01,1,334,1965,4649,8586,6477,1909,189,12,24122,NaN
18,Basilicata,2021-01-01,0,21,134,521,1089,903,269,35,3,2975,NaN
19,Calabria,2021-01-01,1,106,776,2724,4218,3066,872,77,11,11851,NaN
20,Sicilia,2021-01-01,0,864,3361,7729,11538,8177,2124,197,26,34016,NaN
21,Sardegna,2021-01-01,1,64,392,1292,2417,2394,871,96,14,7541,NaN
22,Italia,2021-01-01,5,2975,17638,59629,114332,90503,26223,2700,366,314371,NaN

In [16]:
# Elimina colonne specifiche
cols_to_drop = ['Note']
madre_2021 = madre_2021.drop(columns=cols_to_drop, errors='ignore') 
madre_2021

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2021-01-01,1,97,820,3813,7268,5629,1516,176,25,19345
1,Valle d'Aosta/Vallée d'Aoste,2021-01-01,0,2,31,141,221,150,33,1,0,579
2,Liguria,2021-01-01,0,31,199,1059,2288,1703,538,63,8,5889
3,Lombardia,2021-01-01,0,249,1619,7839,18424,15006,4124,383,42,47686
4,Trentino-Alto Adige/Südtirol,2021-01-01,0,33,390,1660,2702,1760,468,35,3,7051
5,Provincia Autonoma di Bolzano,2021-01-01,0,25,251,975,1479,903,237,19,2,3891
6,Provincia Autonoma di Trento,2021-01-01,0,8,139,685,1223,857,231,16,1,3160
7,Veneto,2021-01-01,0,99,816,4165,8951,6936,2060,184,20,23231
8,Friuli-Venezia Giulia,2021-01-01,0,17,227,976,1977,1534,447,53,3,5234
9,Emilia-Romagna,2021-01-01,0,87,736,3416,7475,6005,1773,211,38,19741
10,Toscana,2021-01-01,0,71,534,2540,5944,5341,1653,174,21,16278
11,Umbria,2021-01-01,0,13,161,696,1370,1178,374,35,7,3834
12,Marche,2021-01-01,0,32,276,1199,2630,2206,656,52,5,7056
13,Lazio,2021-01-01,0,163,1303,4794,10170,9480,3058,404,68,29440
14,Abruzzo,2021-01-01,0,53,355,1262,2379,2128,658,61,14,6910
15,Molise,2021-01-01,0,16,92,279,493,465,134,11,1,1491
16,Campania,2021-01-01,1,623,3451,8875,14192,9965,2686,263,45,40101
17,Puglia,2021-01-01,1,334,1965,4649,8586,6477,1909,189,12,24122
18,Basilicata,2021-01-01,0,21,134,521,1089,903,269,35,3,2975
19,Calabria,2021-01-01,1,106,776,2724,4218,3066,872,77,11,11851
20,Sicilia,2021-01-01,0,864,3361,7729,11538,8177,2124,197,26,34016
21,Sardegna,2021-01-01,1,64,392,1292,2417,2394,871,96,14,7541
22,Italia,2021-01-01,5,2975,17638,59629,114332,90503,26223,2700,366,314371

In [17]:
# Gestisci NaN 
madre_2021 = madre_2021.dropna()
madre_2021

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2021-01-01,1,97,820,3813,7268,5629,1516,176,25,19345
1,Valle d'Aosta/Vallée d'Aoste,2021-01-01,0,2,31,141,221,150,33,1,0,579
2,Liguria,2021-01-01,0,31,199,1059,2288,1703,538,63,8,5889
3,Lombardia,2021-01-01,0,249,1619,7839,18424,15006,4124,383,42,47686
4,Trentino-Alto Adige/Südtirol,2021-01-01,0,33,390,1660,2702,1760,468,35,3,7051
5,Provincia Autonoma di Bolzano,2021-01-01,0,25,251,975,1479,903,237,19,2,3891
6,Provincia Autonoma di Trento,2021-01-01,0,8,139,685,1223,857,231,16,1,3160
7,Veneto,2021-01-01,0,99,816,4165,8951,6936,2060,184,20,23231
8,Friuli-Venezia Giulia,2021-01-01,0,17,227,976,1977,1534,447,53,3,5234
9,Emilia-Romagna,2021-01-01,0,87,736,3416,7475,6005,1773,211,38,19741
10,Toscana,2021-01-01,0,71,534,2540,5944,5341,1653,174,21,16278
11,Umbria,2021-01-01,0,13,161,696,1370,1178,374,35,7,3834
12,Marche,2021-01-01,0,32,276,1199,2630,2206,656,52,5,7056
13,Lazio,2021-01-01,0,163,1303,4794,10170,9480,3058,404,68,29440
14,Abruzzo,2021-01-01,0,53,355,1262,2379,2128,658,61,14,6910
15,Molise,2021-01-01,0,16,92,279,493,465,134,11,1,1491
16,Campania,2021-01-01,1,623,3451,8875,14192,9965,2686,263,45,40101
17,Puglia,2021-01-01,1,334,1965,4649,8586,6477,1909,189,12,24122
18,Basilicata,2021-01-01,0,21,134,521,1089,903,269,35,3,2975
19,Calabria,2021-01-01,1,106,776,2724,4218,3066,872,77,11,11851
20,Sicilia,2021-01-01,0,864,3361,7729,11538,8177,2124,197,26,34016
21,Sardegna,2021-01-01,1,64,392,1292,2417,2394,871,96,14,7541
22,Italia,2021-01-01,5,2975,17638,59629,114332,90503,26223,2700,366,314371

In [18]:
# Esporto in CSV
madre_2021.to_csv('madre_2021.csv', index=False, encoding='utf-8', na_rep=None)

In [19]:
#Importiamo il database Nati per cittadinanza dei genitori ed età della madre 2022
madre_2022 = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (5).csv')
madre_2022

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale,Note
0,Piemonte,2022,0,87,817,3444,7335,5395,1598,183,27,18886,NaN
1,Valle d'Aosta/Vallée d'Aoste,2022,0,4,26,148,257,168,32,8,0,643,NaN
2,Liguria,2022,0,44,237,958,2326,1716,552,68,14,5915,NaN
3,Lombardia,2022,0,257,1660,7582,18260,14448,4135,491,60,46893,NaN
4,Trentino-Alto Adige/Südtirol,2022,0,34,318,1564,2667,1660,411,46,3,6703,NaN
5,Provincia Autonoma di Bolzano,2022,0,22,212,926,1480,819,180,22,1,3662,NaN
6,Provincia Autonoma di Trento,2022,0,12,106,638,1187,841,231,24,2,3041,NaN
7,Veneto,2022,0,82,859,4128,8727,6610,2031,223,23,22683,NaN
8,Friuli-Venezia Giulia,2022,0,24,223,956,1976,1528,464,69,6,5246,NaN
9,Emilia-Romagna,2022,1,93,734,3453,7644,5994,1804,253,23,19999,NaN
10,Toscana,2022,0,68,504,2456,5880,5035,1622,251,30,15846,NaN
11,Umbria,2022,0,16,164,652,1383,1066,342,36,4,3663,NaN
12,Marche,2022,0,36,267,1194,2602,2054,612,75,12,6852,NaN
13,Lazio,2022,0,156,1249,4486,10166,8839,3145,503,67,28611,NaN
14,Abruzzo,2022,1,44,341,1144,2394,1959,682,92,12,6669,NaN
15,Molise,2022,0,13,69,292,566,422,122,21,2,1507,NaN
16,Campania,2022,2,561,3360,9101,15196,9815,2575,360,57,41027,NaN
17,Puglia,2022,0,328,1752,4963,8578,6432,1829,216,28,24126,NaN
18,Basilicata,2022,0,16,117,493,1063,874,266,35,2,2866,NaN
19,Calabria,2022,0,118,839,2806,4353,3167,830,91,22,12226,NaN
20,Sicilia,2022,1,828,3368,7695,11558,7807,2132,267,46,33702,NaN
21,Sardegna,2022,1,68,434,1194,2293,2143,798,110,13,7054,NaN
22,Italia,2022,6,2877,17338,58709,115224,87132,25982,3398,451,311117,NaN

In [20]:
#Cambio il formato data
madre_2022['Anno'] = pd.to_datetime(madre_2022['Anno'], format='%Y')
madre_2022

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale,Note
0,Piemonte,2022-01-01,0,87,817,3444,7335,5395,1598,183,27,18886,NaN
1,Valle d'Aosta/Vallée d'Aoste,2022-01-01,0,4,26,148,257,168,32,8,0,643,NaN
2,Liguria,2022-01-01,0,44,237,958,2326,1716,552,68,14,5915,NaN
3,Lombardia,2022-01-01,0,257,1660,7582,18260,14448,4135,491,60,46893,NaN
4,Trentino-Alto Adige/Südtirol,2022-01-01,0,34,318,1564,2667,1660,411,46,3,6703,NaN
5,Provincia Autonoma di Bolzano,2022-01-01,0,22,212,926,1480,819,180,22,1,3662,NaN
6,Provincia Autonoma di Trento,2022-01-01,0,12,106,638,1187,841,231,24,2,3041,NaN
7,Veneto,2022-01-01,0,82,859,4128,8727,6610,2031,223,23,22683,NaN
8,Friuli-Venezia Giulia,2022-01-01,0,24,223,956,1976,1528,464,69,6,5246,NaN
9,Emilia-Romagna,2022-01-01,1,93,734,3453,7644,5994,1804,253,23,19999,NaN
10,Toscana,2022-01-01,0,68,504,2456,5880,5035,1622,251,30,15846,NaN
11,Umbria,2022-01-01,0,16,164,652,1383,1066,342,36,4,3663,NaN
12,Marche,2022-01-01,0,36,267,1194,2602,2054,612,75,12,6852,NaN
13,Lazio,2022-01-01,0,156,1249,4486,10166,8839,3145,503,67,28611,NaN
14,Abruzzo,2022-01-01,1,44,341,1144,2394,1959,682,92,12,6669,NaN
15,Molise,2022-01-01,0,13,69,292,566,422,122,21,2,1507,NaN
16,Campania,2022-01-01,2,561,3360,9101,15196,9815,2575,360,57,41027,NaN
17,Puglia,2022-01-01,0,328,1752,4963,8578,6432,1829,216,28,24126,NaN
18,Basilicata,2022-01-01,0,16,117,493,1063,874,266,35,2,2866,NaN
19,Calabria,2022-01-01,0,118,839,2806,4353,3167,830,91,22,12226,NaN
20,Sicilia,2022-01-01,1,828,3368,7695,11558,7807,2132,267,46,33702,NaN
21,Sardegna,2022-01-01,1,68,434,1194,2293,2143,798,110,13,7054,NaN
22,Italia,2022-01-01,6,2877,17338,58709,115224,87132,25982,3398,451,311117,NaN

In [21]:
# Elimina colonne specifiche
cols_to_drop = ['Note']
madre_2022 = madre_2022.drop(columns=cols_to_drop, errors='ignore') 
madre_2022

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2022-01-01,0,87,817,3444,7335,5395,1598,183,27,18886
1,Valle d'Aosta/Vallée d'Aoste,2022-01-01,0,4,26,148,257,168,32,8,0,643
2,Liguria,2022-01-01,0,44,237,958,2326,1716,552,68,14,5915
3,Lombardia,2022-01-01,0,257,1660,7582,18260,14448,4135,491,60,46893
4,Trentino-Alto Adige/Südtirol,2022-01-01,0,34,318,1564,2667,1660,411,46,3,6703
5,Provincia Autonoma di Bolzano,2022-01-01,0,22,212,926,1480,819,180,22,1,3662
6,Provincia Autonoma di Trento,2022-01-01,0,12,106,638,1187,841,231,24,2,3041
7,Veneto,2022-01-01,0,82,859,4128,8727,6610,2031,223,23,22683
8,Friuli-Venezia Giulia,2022-01-01,0,24,223,956,1976,1528,464,69,6,5246
9,Emilia-Romagna,2022-01-01,1,93,734,3453,7644,5994,1804,253,23,19999
10,Toscana,2022-01-01,0,68,504,2456,5880,5035,1622,251,30,15846
11,Umbria,2022-01-01,0,16,164,652,1383,1066,342,36,4,3663
12,Marche,2022-01-01,0,36,267,1194,2602,2054,612,75,12,6852
13,Lazio,2022-01-01,0,156,1249,4486,10166,8839,3145,503,67,28611
14,Abruzzo,2022-01-01,1,44,341,1144,2394,1959,682,92,12,6669
15,Molise,2022-01-01,0,13,69,292,566,422,122,21,2,1507
16,Campania,2022-01-01,2,561,3360,9101,15196,9815,2575,360,57,41027
17,Puglia,2022-01-01,0,328,1752,4963,8578,6432,1829,216,28,24126
18,Basilicata,2022-01-01,0,16,117,493,1063,874,266,35,2,2866
19,Calabria,2022-01-01,0,118,839,2806,4353,3167,830,91,22,12226
20,Sicilia,2022-01-01,1,828,3368,7695,11558,7807,2132,267,46,33702
21,Sardegna,2022-01-01,1,68,434,1194,2293,2143,798,110,13,7054
22,Italia,2022-01-01,6,2877,17338,58709,115224,87132,25982,3398,451,311117

In [22]:
#  Gestisci NaN 
madre_2022 = madre_2022.dropna()
madre_2022

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2022-01-01,0,87,817,3444,7335,5395,1598,183,27,18886
1,Valle d'Aosta/Vallée d'Aoste,2022-01-01,0,4,26,148,257,168,32,8,0,643
2,Liguria,2022-01-01,0,44,237,958,2326,1716,552,68,14,5915
3,Lombardia,2022-01-01,0,257,1660,7582,18260,14448,4135,491,60,46893
4,Trentino-Alto Adige/Südtirol,2022-01-01,0,34,318,1564,2667,1660,411,46,3,6703
5,Provincia Autonoma di Bolzano,2022-01-01,0,22,212,926,1480,819,180,22,1,3662
6,Provincia Autonoma di Trento,2022-01-01,0,12,106,638,1187,841,231,24,2,3041
7,Veneto,2022-01-01,0,82,859,4128,8727,6610,2031,223,23,22683
8,Friuli-Venezia Giulia,2022-01-01,0,24,223,956,1976,1528,464,69,6,5246
9,Emilia-Romagna,2022-01-01,1,93,734,3453,7644,5994,1804,253,23,19999
10,Toscana,2022-01-01,0,68,504,2456,5880,5035,1622,251,30,15846
11,Umbria,2022-01-01,0,16,164,652,1383,1066,342,36,4,3663
12,Marche,2022-01-01,0,36,267,1194,2602,2054,612,75,12,6852
13,Lazio,2022-01-01,0,156,1249,4486,10166,8839,3145,503,67,28611
14,Abruzzo,2022-01-01,1,44,341,1144,2394,1959,682,92,12,6669
15,Molise,2022-01-01,0,13,69,292,566,422,122,21,2,1507
16,Campania,2022-01-01,2,561,3360,9101,15196,9815,2575,360,57,41027
17,Puglia,2022-01-01,0,328,1752,4963,8578,6432,1829,216,28,24126
18,Basilicata,2022-01-01,0,16,117,493,1063,874,266,35,2,2866
19,Calabria,2022-01-01,0,118,839,2806,4353,3167,830,91,22,12226
20,Sicilia,2022-01-01,1,828,3368,7695,11558,7807,2132,267,46,33702
21,Sardegna,2022-01-01,1,68,434,1194,2293,2143,798,110,13,7054
22,Italia,2022-01-01,6,2877,17338,58709,115224,87132,25982,3398,451,311117

In [23]:
# Esporto in CSV
madre_2022.to_csv('madre_2022.csv', index=False, encoding='utf-8', na_rep=None)

In [24]:
#Importiamo il database Nati per cittadinanza dei genitori ed età della madre 2023
madre_2023 = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (6).csv')
madre_2023

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale,Note
0,Piemonte,2023,0,85,703,3303,7065,5230,1507,183,25,18101,NaN
1,Valle d'Aosta/Vallée d'Aoste,2023,0,1,28,112,225,158,37,6,0,567,NaN
2,Liguria,2023,0,34,227,960,2255,1677,545,79,9,5786,NaN
3,Lombardia,2023,0,214,1593,7238,17932,13912,3966,492,63,45410,NaN
4,Trentino-Alto Adige/Südtirol,2023,0,21,321,1464,2543,1585,415,58,2,6409,NaN
5,Provincia Autonoma di Bolzano,2023,0,14,200,893,1407,791,183,29,2,3519,NaN
6,Provincia Autonoma di Trento,2023,0,7,121,571,1136,794,232,29,0,2890,NaN
7,Veneto,2023,0,114,723,3679,8587,6453,1867,229,22,21674,NaN
8,Friuli-Venezia Giulia,2023,0,23,210,926,1844,1492,397,40,7,4939,NaN
9,Emilia-Romagna,2023,0,86,689,3270,7269,5732,1799,212,26,19083,NaN
10,Toscana,2023,0,56,468,2223,5780,4828,1497,216,22,15090,NaN
11,Umbria,2023,0,21,117,621,1347,1082,344,29,4,3565,NaN
12,Marche,2023,0,27,256,1111,2560,2114,618,97,14,6797,NaN
13,Lazio,2023,1,163,1179,4394,9446,8435,2826,458,71,26973,NaN
14,Abruzzo,2023,0,47,295,1098,2265,1878,573,84,8,6248,NaN
15,Molise,2023,0,15,98,284,483,420,156,16,1,1473,NaN
16,Campania,2023,1,548,3065,8594,14348,9880,2664,336,73,39509,NaN
17,Puglia,2023,0,308,1665,4521,8398,6397,1874,219,29,23411,NaN
18,Basilicata,2023,0,16,128,476,981,878,267,33,5,2784,NaN
19,Calabria,2023,0,99,786,2611,4301,3217,909,104,21,12048,NaN
20,Sicilia,2023,3,795,3031,6980,11262,7906,2182,244,49,32452,NaN
21,Sardegna,2023,1,47,360,1044,2226,2042,782,110,17,6629,NaN
22,Italia,2023,6,2720,15942,54909,111117,85316,25225,3245,468,298948,NaN

In [25]:
# Elimina colonne specifiche
cols_to_drop = ['Note']
madre_2023 = madre_2023.drop(columns=cols_to_drop, errors='ignore') 
madre_2023

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2023,0,85,703,3303,7065,5230,1507,183,25,18101
1,Valle d'Aosta/Vallée d'Aoste,2023,0,1,28,112,225,158,37,6,0,567
2,Liguria,2023,0,34,227,960,2255,1677,545,79,9,5786
3,Lombardia,2023,0,214,1593,7238,17932,13912,3966,492,63,45410
4,Trentino-Alto Adige/Südtirol,2023,0,21,321,1464,2543,1585,415,58,2,6409
5,Provincia Autonoma di Bolzano,2023,0,14,200,893,1407,791,183,29,2,3519
6,Provincia Autonoma di Trento,2023,0,7,121,571,1136,794,232,29,0,2890
7,Veneto,2023,0,114,723,3679,8587,6453,1867,229,22,21674
8,Friuli-Venezia Giulia,2023,0,23,210,926,1844,1492,397,40,7,4939
9,Emilia-Romagna,2023,0,86,689,3270,7269,5732,1799,212,26,19083
10,Toscana,2023,0,56,468,2223,5780,4828,1497,216,22,15090
11,Umbria,2023,0,21,117,621,1347,1082,344,29,4,3565
12,Marche,2023,0,27,256,1111,2560,2114,618,97,14,6797
13,Lazio,2023,1,163,1179,4394,9446,8435,2826,458,71,26973
14,Abruzzo,2023,0,47,295,1098,2265,1878,573,84,8,6248
15,Molise,2023,0,15,98,284,483,420,156,16,1,1473
16,Campania,2023,1,548,3065,8594,14348,9880,2664,336,73,39509
17,Puglia,2023,0,308,1665,4521,8398,6397,1874,219,29,23411
18,Basilicata,2023,0,16,128,476,981,878,267,33,5,2784
19,Calabria,2023,0,99,786,2611,4301,3217,909,104,21,12048
20,Sicilia,2023,3,795,3031,6980,11262,7906,2182,244,49,32452
21,Sardegna,2023,1,47,360,1044,2226,2042,782,110,17,6629
22,Italia,2023,6,2720,15942,54909,111117,85316,25225,3245,468,298948

In [26]:
#  Gestisci NaN 
madre_2023 = madre_2023.dropna()
madre_2023

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2023,0,85,703,3303,7065,5230,1507,183,25,18101
1,Valle d'Aosta/Vallée d'Aoste,2023,0,1,28,112,225,158,37,6,0,567
2,Liguria,2023,0,34,227,960,2255,1677,545,79,9,5786
3,Lombardia,2023,0,214,1593,7238,17932,13912,3966,492,63,45410
4,Trentino-Alto Adige/Südtirol,2023,0,21,321,1464,2543,1585,415,58,2,6409
5,Provincia Autonoma di Bolzano,2023,0,14,200,893,1407,791,183,29,2,3519
6,Provincia Autonoma di Trento,2023,0,7,121,571,1136,794,232,29,0,2890
7,Veneto,2023,0,114,723,3679,8587,6453,1867,229,22,21674
8,Friuli-Venezia Giulia,2023,0,23,210,926,1844,1492,397,40,7,4939
9,Emilia-Romagna,2023,0,86,689,3270,7269,5732,1799,212,26,19083
10,Toscana,2023,0,56,468,2223,5780,4828,1497,216,22,15090
11,Umbria,2023,0,21,117,621,1347,1082,344,29,4,3565
12,Marche,2023,0,27,256,1111,2560,2114,618,97,14,6797
13,Lazio,2023,1,163,1179,4394,9446,8435,2826,458,71,26973
14,Abruzzo,2023,0,47,295,1098,2265,1878,573,84,8,6248
15,Molise,2023,0,15,98,284,483,420,156,16,1,1473
16,Campania,2023,1,548,3065,8594,14348,9880,2664,336,73,39509
17,Puglia,2023,0,308,1665,4521,8398,6397,1874,219,29,23411
18,Basilicata,2023,0,16,128,476,981,878,267,33,5,2784
19,Calabria,2023,0,99,786,2611,4301,3217,909,104,21,12048
20,Sicilia,2023,3,795,3031,6980,11262,7906,2182,244,49,32452
21,Sardegna,2023,1,47,360,1044,2226,2042,782,110,17,6629
22,Italia,2023,6,2720,15942,54909,111117,85316,25225,3245,468,298948

In [27]:
#Cambio il formato data
madre_2023['Anno'] = pd.to_datetime(madre_2023['Anno'], format='%Y')
madre_2023

,Regione,Anno,Meno di 15 anni,15-19 anni,20-24 anni,25-29 anni,30-34 anni,35-39 anni,40-44 anni,45-49 anni,50 anni e più,Totale
0,Piemonte,2023-01-01,0,85,703,3303,7065,5230,1507,183,25,18101
1,Valle d'Aosta/Vallée d'Aoste,2023-01-01,0,1,28,112,225,158,37,6,0,567
2,Liguria,2023-01-01,0,34,227,960,2255,1677,545,79,9,5786
3,Lombardia,2023-01-01,0,214,1593,7238,17932,13912,3966,492,63,45410
4,Trentino-Alto Adige/Südtirol,2023-01-01,0,21,321,1464,2543,1585,415,58,2,6409
5,Provincia Autonoma di Bolzano,2023-01-01,0,14,200,893,1407,791,183,29,2,3519
6,Provincia Autonoma di Trento,2023-01-01,0,7,121,571,1136,794,232,29,0,2890
7,Veneto,2023-01-01,0,114,723,3679,8587,6453,1867,229,22,21674
8,Friuli-Venezia Giulia,2023-01-01,0,23,210,926,1844,1492,397,40,7,4939
9,Emilia-Romagna,2023-01-01,0,86,689,3270,7269,5732,1799,212,26,19083
10,Toscana,2023-01-01,0,56,468,2223,5780,4828,1497,216,22,15090
11,Umbria,2023-01-01,0,21,117,621,1347,1082,344,29,4,3565
12,Marche,2023-01-01,0,27,256,1111,2560,2114,618,97,14,6797
13,Lazio,2023-01-01,1,163,1179,4394,9446,8435,2826,458,71,26973
14,Abruzzo,2023-01-01,0,47,295,1098,2265,1878,573,84,8,6248
15,Molise,2023-01-01,0,15,98,284,483,420,156,16,1,1473
16,Campania,2023-01-01,1,548,3065,8594,14348,9880,2664,336,73,39509
17,Puglia,2023-01-01,0,308,1665,4521,8398,6397,1874,219,29,23411
18,Basilicata,2023-01-01,0,16,128,476,981,878,267,33,5,2784
19,Calabria,2023-01-01,0,99,786,2611,4301,3217,909,104,21,12048
20,Sicilia,2023-01-01,3,795,3031,6980,11262,7906,2182,244,49,32452
21,Sardegna,2023-01-01,1,47,360,1044,2226,2042,782,110,17,6629
22,Italia,2023-01-01,6,2720,15942,54909,111117,85316,25225,3245,468,298948

In [28]:
# Esporto in CSV
madre_2023.to_csv('madre_2023.csv', index=False, encoding='utf-8', na_rep=None)

In [29]:
#Importiamo il database dei Nomi Femminili più diffusi per Regione
Nomif = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (10).csv')
Nomif

,Territorio,Anno,Punteggio,Nome,Nati (valore assoluto),Nati (valore percentuale)
0,Piemonte,1999,1,GIULIA,720,4.36
1,Piemonte,1999,2,ALESSIA,669,4.05
2,Piemonte,1999,3,MARTINA,666,4.04
3,Piemonte,1999,4,CHIARA,564,3.42
4,Piemonte,1999,5,SARA,555,3.36
...,...,...,...,...,...,...
7844,Provincia Autonoma di Trento,2023,7,CAMILLA,30,1.65
7845,Provincia Autonoma di Trento,2023,8,EMILY,27,1.49
7846,Provincia Autonoma di Trento,2023,9,ADELE,23,1.27
7847,Provincia Autonoma di Trento,2023,9,ANNA,23,1.27
7848,Provincia Autonoma di Trento,2023,10,GIULIA,22,1.21

In [30]:
#  Gestisci NaN 
Nomif = Nomif.dropna()
Nomif

,Territorio,Anno,Punteggio,Nome,Nati (valore assoluto),Nati (valore percentuale)
0,Piemonte,1999,1,GIULIA,720,4.36
1,Piemonte,1999,2,ALESSIA,669,4.05
2,Piemonte,1999,3,MARTINA,666,4.04
3,Piemonte,1999,4,CHIARA,564,3.42
4,Piemonte,1999,5,SARA,555,3.36
...,...,...,...,...,...,...
7844,Provincia Autonoma di Trento,2023,7,CAMILLA,30,1.65
7845,Provincia Autonoma di Trento,2023,8,EMILY,27,1.49
7846,Provincia Autonoma di Trento,2023,9,ADELE,23,1.27
7847,Provincia Autonoma di Trento,2023,9,ANNA,23,1.27
7848,Provincia Autonoma di Trento,2023,10,GIULIA,22,1.21

In [31]:
#Cambio il formato data
Nomif['Anno'] = pd.to_datetime(Nomif['Anno'], format='%Y')
Nomif

,Territorio,Anno,Punteggio,Nome,Nati (valore assoluto),Nati (valore percentuale)
0,Piemonte,1999-01-01,1,GIULIA,720,4.36
1,Piemonte,1999-01-01,2,ALESSIA,669,4.05
2,Piemonte,1999-01-01,3,MARTINA,666,4.04
3,Piemonte,1999-01-01,4,CHIARA,564,3.42
4,Piemonte,1999-01-01,5,SARA,555,3.36
...,...,...,...,...,...,...
7844,Provincia Autonoma di Trento,2023-01-01,7,CAMILLA,30,1.65
7845,Provincia Autonoma di Trento,2023-01-01,8,EMILY,27,1.49
7846,Provincia Autonoma di Trento,2023-01-01,9,ADELE,23,1.27
7847,Provincia Autonoma di Trento,2023-01-01,9,ANNA,23,1.27
7848,Provincia Autonoma di Trento,2023-01-01,10,GIULIA,22,1.21

In [32]:
# Esporto in CSV
Nomif.to_csv('nomif.csv', index=False, encoding='utf-8', na_rep=None)

In [33]:
#Importiamo il database dei Nomi maschili più diffusi per Regione
Nomi = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (7).csv')
Nomi

,Territorio,Anno,Punteggio,Nome,Nati (valore assoluto),Nati (valore percentuale)
0,Piemonte,1999,1,ANDREA,961,5.39
1,Piemonte,1999,2,MATTEO,742,4.16
2,Piemonte,1999,3,ALESSANDRO,740,4.15
3,Piemonte,1999,4,LORENZO,695,3.90
4,Piemonte,1999,5,LUCA,687,3.85
...,...,...,...,...,...,...
7112,Provincia Autonoma di Trento,2023,9,GABRIELE,27,1.37
7113,Provincia Autonoma di Trento,2023,9,NICOLO',27,1.37
7114,Provincia Autonoma di Trento,2023,10,ALESSANDRO,26,1.32
7115,Provincia Autonoma di Trento,2023,10,GABRIEL,26,1.32
7116,Provincia Autonoma di Trento,2023,10,GIACOMO,26,1.32

In [34]:
#  Gestisci NaN 
Nomi = Nomi.dropna()
Nomi

,Territorio,Anno,Punteggio,Nome,Nati (valore assoluto),Nati (valore percentuale)
0,Piemonte,1999,1,ANDREA,961,5.39
1,Piemonte,1999,2,MATTEO,742,4.16
2,Piemonte,1999,3,ALESSANDRO,740,4.15
3,Piemonte,1999,4,LORENZO,695,3.90
4,Piemonte,1999,5,LUCA,687,3.85
...,...,...,...,...,...,...
7112,Provincia Autonoma di Trento,2023,9,GABRIELE,27,1.37
7113,Provincia Autonoma di Trento,2023,9,NICOLO',27,1.37
7114,Provincia Autonoma di Trento,2023,10,ALESSANDRO,26,1.32
7115,Provincia Autonoma di Trento,2023,10,GABRIEL,26,1.32
7116,Provincia Autonoma di Trento,2023,10,GIACOMO,26,1.32

In [35]:
#Cambio il formato data
Nomi['Anno'] = pd.to_datetime(Nomi['Anno'], format='%Y')
Nomi

,Territorio,Anno,Punteggio,Nome,Nati (valore assoluto),Nati (valore percentuale)
0,Piemonte,1999-01-01,1,ANDREA,961,5.39
1,Piemonte,1999-01-01,2,MATTEO,742,4.16
2,Piemonte,1999-01-01,3,ALESSANDRO,740,4.15
3,Piemonte,1999-01-01,4,LORENZO,695,3.90
4,Piemonte,1999-01-01,5,LUCA,687,3.85
...,...,...,...,...,...,...
7112,Provincia Autonoma di Trento,2023-01-01,9,GABRIELE,27,1.37
7113,Provincia Autonoma di Trento,2023-01-01,9,NICOLO',27,1.37
7114,Provincia Autonoma di Trento,2023-01-01,10,ALESSANDRO,26,1.32
7115,Provincia Autonoma di Trento,2023-01-01,10,GABRIEL,26,1.32
7116,Provincia Autonoma di Trento,2023-01-01,10,GIACOMO,26,1.32

In [36]:
# Esporto in CSV
Nomi.to_csv('nomi.csv', index=False, encoding='utf-8', na_rep=None)

In [37]:
#Importiamo il database Nati coniugati e non coniugati 2020
coniugatienon_2020 = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (14).csv')
coniugatienon_2020

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %,Genitori già coniugati - V.A.,Genitori già coniugati - %,Totale - V.A.,Note
0,Italia,2020,118697,29.32,259823,64.17,26372,6.51,404892,NaN
1,Lombardia,2020,20284,29.30,44645,64.48,4306,6.22,69235,NaN
2,Campania,2020,9245,20.51,32560,72.23,3273,7.26,45078,NaN
3,Sicilia,2020,8897,23.71,26253,69.97,2370,6.32,37520,NaN
4,Lazio,2020,13099,34.49,22153,58.32,2730,7.19,37982,NaN
5,Veneto,2020,10007,30.63,20887,63.93,1778,5.44,32672,NaN
6,Emilia-Romagna,2020,9550,31.98,18604,62.30,1707,5.72,29861,NaN
7,Puglia,2020,6835,25.84,17957,67.88,1663,6.29,26455,NaN
8,Piemonte,2020,8984,33.14,16140,59.54,1983,7.32,27107,NaN
9,Toscana,2020,8259,36.90,12474,55.74,1647,7.36,22380,NaN
10,Calabria,2020,2490,17.83,10616,76.01,860,6.16,13966,NaN
11,Marche,2020,3091,32.77,5763,61.10,578,6.13,9432,NaN
12,Liguria,2020,2797,31.96,5222,59.67,733,8.38,8752,NaN
13,Abruzzo,2020,2473,30.02,5201,63.14,563,6.84,8237,NaN
14,Trentino-Alto Adige/Südtirol,2020,3687,39.91,5105,55.25,447,4.84,9239,NaN
15,Friuli-Venezia Giulia,2020,2472,33.25,4514,60.72,448,6.03,7434,NaN
16,Sardegna,2020,3340,40.43,4314,52.21,608,7.36,8262,NaN
17,Umbria,2020,1853,35.17,3071,58.30,344,6.53,5268,NaN
18,Provincia Autonoma di Bolzano,2020,2227,42.90,2753,53.03,211,4.06,5191,NaN
19,Basilicata,2020,604,17.14,2748,78.00,171,4.85,3523,NaN
20,Provincia Autonoma di Trento,2020,1460,36.07,2352,58.10,236,5.83,4048,NaN
21,Molise,2020,435,25.39,1162,67.83,116,6.77,1713,NaN
22,Valle d'Aosta/Vallée d'Aoste,2020,295,38.02,434,55.93,47,6.06,776,NaN

In [38]:
cols_to_drop = ['Genitori già coniugati - V.A.','Genitori già coniugati - %','Totale - V.A.','Note']
coniugatienon_2020 = coniugatienon_2020.drop(columns=cols_to_drop, errors='ignore') 
coniugatienon_2020

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %
0,Italia,2020,118697,29.32,259823,64.17
1,Lombardia,2020,20284,29.30,44645,64.48
2,Campania,2020,9245,20.51,32560,72.23
3,Sicilia,2020,8897,23.71,26253,69.97
4,Lazio,2020,13099,34.49,22153,58.32
5,Veneto,2020,10007,30.63,20887,63.93
6,Emilia-Romagna,2020,9550,31.98,18604,62.30
7,Puglia,2020,6835,25.84,17957,67.88
8,Piemonte,2020,8984,33.14,16140,59.54
9,Toscana,2020,8259,36.90,12474,55.74
10,Calabria,2020,2490,17.83,10616,76.01
11,Marche,2020,3091,32.77,5763,61.10
12,Liguria,2020,2797,31.96,5222,59.67
13,Abruzzo,2020,2473,30.02,5201,63.14
14,Trentino-Alto Adige/Südtirol,2020,3687,39.91,5105,55.25
15,Friuli-Venezia Giulia,2020,2472,33.25,4514,60.72
16,Sardegna,2020,3340,40.43,4314,52.21
17,Umbria,2020,1853,35.17,3071,58.30
18,Provincia Autonoma di Bolzano,2020,2227,42.90,2753,53.03
19,Basilicata,2020,604,17.14,2748,78.00
20,Provincia Autonoma di Trento,2020,1460,36.07,2352,58.10
21,Molise,2020,435,25.39,1162,67.83
22,Valle d'Aosta/Vallée d'Aoste,2020,295,38.02,434,55.93

In [39]:
#Cambio il formato data
coniugatienon_2020['Anno'] = pd.to_datetime(coniugatienon_2020['Anno'], format='%Y')
coniugatienon_2020

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %
0,Italia,2020-01-01,118697,29.32,259823,64.17
1,Lombardia,2020-01-01,20284,29.30,44645,64.48
2,Campania,2020-01-01,9245,20.51,32560,72.23
3,Sicilia,2020-01-01,8897,23.71,26253,69.97
4,Lazio,2020-01-01,13099,34.49,22153,58.32
5,Veneto,2020-01-01,10007,30.63,20887,63.93
6,Emilia-Romagna,2020-01-01,9550,31.98,18604,62.30
7,Puglia,2020-01-01,6835,25.84,17957,67.88
8,Piemonte,2020-01-01,8984,33.14,16140,59.54
9,Toscana,2020-01-01,8259,36.90,12474,55.74
10,Calabria,2020-01-01,2490,17.83,10616,76.01
11,Marche,2020-01-01,3091,32.77,5763,61.10
12,Liguria,2020-01-01,2797,31.96,5222,59.67
13,Abruzzo,2020-01-01,2473,30.02,5201,63.14
14,Trentino-Alto Adige/Südtirol,2020-01-01,3687,39.91,5105,55.25
15,Friuli-Venezia Giulia,2020-01-01,2472,33.25,4514,60.72
16,Sardegna,2020-01-01,3340,40.43,4314,52.21
17,Umbria,2020-01-01,1853,35.17,3071,58.30
18,Provincia Autonoma di Bolzano,2020-01-01,2227,42.90,2753,53.03
19,Basilicata,2020-01-01,604,17.14,2748,78.00
20,Provincia Autonoma di Trento,2020-01-01,1460,36.07,2352,58.10
21,Molise,2020-01-01,435,25.39,1162,67.83
22,Valle d'Aosta/Vallée d'Aoste,2020-01-01,295,38.02,434,55.93

In [40]:
#  Gestisci NaN 
coniugatienon_2020 = coniugatienon_2020.dropna()
coniugatienon_2020

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %
0,Italia,2020-01-01,118697,29.32,259823,64.17
1,Lombardia,2020-01-01,20284,29.30,44645,64.48
2,Campania,2020-01-01,9245,20.51,32560,72.23
3,Sicilia,2020-01-01,8897,23.71,26253,69.97
4,Lazio,2020-01-01,13099,34.49,22153,58.32
5,Veneto,2020-01-01,10007,30.63,20887,63.93
6,Emilia-Romagna,2020-01-01,9550,31.98,18604,62.30
7,Puglia,2020-01-01,6835,25.84,17957,67.88
8,Piemonte,2020-01-01,8984,33.14,16140,59.54
9,Toscana,2020-01-01,8259,36.90,12474,55.74
10,Calabria,2020-01-01,2490,17.83,10616,76.01
11,Marche,2020-01-01,3091,32.77,5763,61.10
12,Liguria,2020-01-01,2797,31.96,5222,59.67
13,Abruzzo,2020-01-01,2473,30.02,5201,63.14
14,Trentino-Alto Adige/Südtirol,2020-01-01,3687,39.91,5105,55.25
15,Friuli-Venezia Giulia,2020-01-01,2472,33.25,4514,60.72
16,Sardegna,2020-01-01,3340,40.43,4314,52.21
17,Umbria,2020-01-01,1853,35.17,3071,58.30
18,Provincia Autonoma di Bolzano,2020-01-01,2227,42.90,2753,53.03
19,Basilicata,2020-01-01,604,17.14,2748,78.00
20,Provincia Autonoma di Trento,2020-01-01,1460,36.07,2352,58.10
21,Molise,2020-01-01,435,25.39,1162,67.83
22,Valle d'Aosta/Vallée d'Aoste,2020-01-01,295,38.02,434,55.93

In [41]:
# Esporto in CSV
coniugatienon_2020.to_csv('coniugatienon_2020.csv', index=False, encoding='utf-8', na_rep=None)

In [42]:
#Importiamo il database Nati per coniugati e non coniugati 2021
coniugatienon_2021 = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (15).csv')
coniugatienon_2021

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %,Genitori già coniugati - V.A.,Genitori già coniugati - %,Totale - V.A.,Note
0,Piemonte,2021,9669,36.21,15079,56.48,1952,7.31,26700,NaN
1,Valle d'Aosta/Vallée d'Aoste,2021,277,37.23,422,56.72,45,6.05,744,NaN
2,Liguria,2021,3256,38.06,4630,54.11,670,7.83,8556,NaN
3,Lombardia,2021,23546,34.17,41117,59.66,4255,6.17,68918,NaN
4,Trentino-Alto Adige/Südtirol,2021,4073,43.50,4924,52.59,366,3.91,9363,NaN
5,Provincia Autonoma di Bolzano,2021,2353,45.49,2669,51.59,151,2.92,5173,NaN
6,Provincia Autonoma di Trento,2021,1720,41.05,2255,53.82,215,5.13,4190,NaN
7,Veneto,2021,11250,34.30,19891,60.65,1658,5.06,32799,NaN
8,Friuli-Venezia Giulia,2021,2609,35.89,4235,58.26,425,5.85,7269,NaN
9,Emilia-Romagna,2021,10911,36.57,17248,57.81,1677,5.62,29836,NaN
10,Toscana,2021,9057,40.09,11944,52.87,1591,7.04,22592,NaN
11,Umbria,2021,2115,40.38,2763,52.75,360,6.87,5238,NaN
12,Marche,2021,3474,37.67,5229,56.70,519,5.63,9222,NaN
13,Lazio,2021,14435,38.77,20192,54.23,2610,7.01,37237,NaN
14,Abruzzo,2021,2922,35.25,4773,57.58,595,7.18,8290,NaN
15,Molise,2021,496,29.44,1056,62.67,133,7.89,1685,NaN
16,Campania,2021,10664,24.57,29622,68.25,3117,7.18,43403,NaN
17,Puglia,2021,8237,31.22,16575,62.83,1569,5.95,26381,NaN
18,Basilicata,2021,683,20.51,2452,73.63,195,5.86,3330,NaN
19,Calabria,2021,2943,22.26,9455,71.53,821,6.21,13219,NaN
20,Sicilia,2021,10240,27.50,24648,66.20,2347,6.30,37235,NaN
21,Sardegna,2021,3477,42.24,4173,50.69,582,7.07,8232,NaN
22,Italia,2021,134334,33.56,240428,60.07,25487,6.37,400249,NaN

In [43]:
cols_to_drop = ['Genitori già coniugati - V.A.','Genitori già coniugati - %','Totale - V.A.','Note']
coniugatienon_2021 = coniugatienon_2021.drop(columns=cols_to_drop, errors='ignore') 
coniugatienon_2021

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %
0,Piemonte,2021,9669,36.21,15079,56.48
1,Valle d'Aosta/Vallée d'Aoste,2021,277,37.23,422,56.72
2,Liguria,2021,3256,38.06,4630,54.11
3,Lombardia,2021,23546,34.17,41117,59.66
4,Trentino-Alto Adige/Südtirol,2021,4073,43.50,4924,52.59
5,Provincia Autonoma di Bolzano,2021,2353,45.49,2669,51.59
6,Provincia Autonoma di Trento,2021,1720,41.05,2255,53.82
7,Veneto,2021,11250,34.30,19891,60.65
8,Friuli-Venezia Giulia,2021,2609,35.89,4235,58.26
9,Emilia-Romagna,2021,10911,36.57,17248,57.81
10,Toscana,2021,9057,40.09,11944,52.87
11,Umbria,2021,2115,40.38,2763,52.75
12,Marche,2021,3474,37.67,5229,56.70
13,Lazio,2021,14435,38.77,20192,54.23
14,Abruzzo,2021,2922,35.25,4773,57.58
15,Molise,2021,496,29.44,1056,62.67
16,Campania,2021,10664,24.57,29622,68.25
17,Puglia,2021,8237,31.22,16575,62.83
18,Basilicata,2021,683,20.51,2452,73.63
19,Calabria,2021,2943,22.26,9455,71.53
20,Sicilia,2021,10240,27.50,24648,66.20
21,Sardegna,2021,3477,42.24,4173,50.69
22,Italia,2021,134334,33.56,240428,60.07

In [44]:
#  Gestisci NaN 
coniugatienon_2021 = coniugatienon_2021.dropna()
coniugatienon_2021

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %
0,Piemonte,2021,9669,36.21,15079,56.48
1,Valle d'Aosta/Vallée d'Aoste,2021,277,37.23,422,56.72
2,Liguria,2021,3256,38.06,4630,54.11
3,Lombardia,2021,23546,34.17,41117,59.66
4,Trentino-Alto Adige/Südtirol,2021,4073,43.50,4924,52.59
5,Provincia Autonoma di Bolzano,2021,2353,45.49,2669,51.59
6,Provincia Autonoma di Trento,2021,1720,41.05,2255,53.82
7,Veneto,2021,11250,34.30,19891,60.65
8,Friuli-Venezia Giulia,2021,2609,35.89,4235,58.26
9,Emilia-Romagna,2021,10911,36.57,17248,57.81
10,Toscana,2021,9057,40.09,11944,52.87
11,Umbria,2021,2115,40.38,2763,52.75
12,Marche,2021,3474,37.67,5229,56.70
13,Lazio,2021,14435,38.77,20192,54.23
14,Abruzzo,2021,2922,35.25,4773,57.58
15,Molise,2021,496,29.44,1056,62.67
16,Campania,2021,10664,24.57,29622,68.25
17,Puglia,2021,8237,31.22,16575,62.83
18,Basilicata,2021,683,20.51,2452,73.63
19,Calabria,2021,2943,22.26,9455,71.53
20,Sicilia,2021,10240,27.50,24648,66.20
21,Sardegna,2021,3477,42.24,4173,50.69
22,Italia,2021,134334,33.56,240428,60.07

In [45]:
#Cambio il formato data
coniugatienon_2021['Anno'] = pd.to_datetime(coniugatienon_2021['Anno'], format='%Y')
coniugatienon_2021

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %
0,Piemonte,2021-01-01,9669,36.21,15079,56.48
1,Valle d'Aosta/Vallée d'Aoste,2021-01-01,277,37.23,422,56.72
2,Liguria,2021-01-01,3256,38.06,4630,54.11
3,Lombardia,2021-01-01,23546,34.17,41117,59.66
4,Trentino-Alto Adige/Südtirol,2021-01-01,4073,43.50,4924,52.59
5,Provincia Autonoma di Bolzano,2021-01-01,2353,45.49,2669,51.59
6,Provincia Autonoma di Trento,2021-01-01,1720,41.05,2255,53.82
7,Veneto,2021-01-01,11250,34.30,19891,60.65
8,Friuli-Venezia Giulia,2021-01-01,2609,35.89,4235,58.26
9,Emilia-Romagna,2021-01-01,10911,36.57,17248,57.81
10,Toscana,2021-01-01,9057,40.09,11944,52.87
11,Umbria,2021-01-01,2115,40.38,2763,52.75
12,Marche,2021-01-01,3474,37.67,5229,56.70
13,Lazio,2021-01-01,14435,38.77,20192,54.23
14,Abruzzo,2021-01-01,2922,35.25,4773,57.58
15,Molise,2021-01-01,496,29.44,1056,62.67
16,Campania,2021-01-01,10664,24.57,29622,68.25
17,Puglia,2021-01-01,8237,31.22,16575,62.83
18,Basilicata,2021-01-01,683,20.51,2452,73.63
19,Calabria,2021-01-01,2943,22.26,9455,71.53
20,Sicilia,2021-01-01,10240,27.50,24648,66.20
21,Sardegna,2021-01-01,3477,42.24,4173,50.69
22,Italia,2021-01-01,134334,33.56,240428,60.07

In [46]:
# Esporto in CSV
coniugatienon_2021.to_csv('coniugatienon_2021.csv', index=False, encoding='utf-8', na_rep=None)

In [76]:
#Importiamo il database Nati per cittadinanza dei genitori ed età della madre 2020
coniugatienon_2022 = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (16).csv')
coniugatienon_2022

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %,Genitori già coniugati - V.A.,Genitori già coniugati - %,Totale - V.A.,Note
0,Piemonte,2022,9816,37.79,14324,55.15,1835,7.06,25975,NaN
1,Valle d'Aosta/Vallée d'Aoste,2022,348,44.56,396,50.70,37,4.74,781,NaN
2,Liguria,2022,3206,37.81,4617,54.45,656,7.74,8479,NaN
3,Lombardia,2022,23733,35.17,39800,58.98,3949,5.85,67482,NaN
4,Trentino-Alto Adige/Südtirol,2022,3872,43.39,4680,52.45,371,4.16,8923,NaN
5,Provincia Autonoma di Bolzano,2022,2188,44.54,2547,51.85,177,3.60,4912,NaN
6,Provincia Autonoma di Trento,2022,1684,41.98,2133,53.18,194,4.84,4011,NaN
7,Veneto,2022,11197,35.26,18895,59.50,1662,5.23,31754,NaN
8,Friuli-Venezia Giulia,2022,2764,37.98,4153,57.07,360,4.95,7277,NaN
9,Emilia-Romagna,2022,10979,37.07,17020,57.47,1616,5.46,29615,NaN
10,Toscana,2022,9177,42.47,11105,51.39,1328,6.15,21610,NaN
11,Umbria,2022,2167,43.99,2411,48.94,348,7.06,4926,NaN
12,Marche,2022,3350,38.12,4910,55.87,528,6.01,8788,NaN
13,Lazio,2022,15079,41.81,18203,50.48,2780,7.71,36062,NaN
14,Abruzzo,2022,2909,36.26,4485,55.90,629,7.84,8023,NaN
15,Molise,2022,549,32.62,1020,60.61,114,6.77,1683,NaN
16,Campania,2022,11686,26.28,29073,65.38,3710,8.34,44469,NaN
17,Puglia,2022,8508,32.35,16090,61.18,1703,6.48,26301,NaN
18,Basilicata,2022,757,23.50,2280,70.79,184,5.71,3221,NaN
19,Calabria,2022,3114,23.15,9366,69.63,971,7.22,13451,NaN
20,Sicilia,2022,10693,29.05,23617,64.16,2500,6.79,36810,NaN
21,Sardegna,2022,3621,47.01,3571,46.36,511,6.63,7703,NaN
22,Italia,2022,137525,34.96,230016,58.48,25792,6.56,393333,NaN

In [77]:
cols_to_drop = ['Genitori già coniugati - V.A.','Genitori già coniugati - %','Totale - V.A.','Note']
coniugatienon_2022 = coniugatienon_2022.drop(columns=cols_to_drop, errors='ignore') 
coniugatienon_2022

,Regione,Anno,Genitori mai coniugati (madre nubile e padre celibe) - V.A.,Genitori mai coniugati (madre nubile e padre celibe) - %,Genitori coniugati - V.A.,Genitori coniugati - %
0,Piemonte,2022,9816,37.79,14324,55.15
1,Valle d'Aosta/Vallée d'Aoste,2022,348,44.56,396,50.70
2,Liguria,2022,3206,37.81,4617,54.45
3,Lombardia,2022,23733,35.17,39800,58.98
4,Trentino-Alto Adige/Südtirol,2022,3872,43.39,4680,52.45
5,Provincia Autonoma di Bolzano,2022,2188,44.54,2547,51.85
6,Provincia Autonoma di Trento,2022,1684,41.98,2133,53.18
7,Veneto,2022,11197,35.26,18895,59.50
8,Friuli-Venezia Giulia,2022,2764,37.98,4153,57.07
9,Emilia-Romagna,2022,10979,37.07,17020,57.47
10,Toscana,2022,9177,42.47,11105,51.39
11,Umbria,2022,2167,43.99,2411,48.94
12,Marche,2022,3350,38.12,4910,55.87
13,Lazio,2022,15079,41.81,18203,50.48
14,Abruzzo,2022,2909,36.26,4485,55.90
15,Molise,2022,549,32.62,1020,60.61
16,Campania,2022,11686,26.28,29073,65.38
17,Puglia,2022,8508,32.35,16090,61.18
18,Basilicata,2022,757,23.50,2280,70.79
19,Calabria,2022,3114,23.15,9366,69.63
20,Sicilia,2022,10693,29.05,23617,64.16
21,Sardegna,2022,3621,47.01,3571,46.36
22,Italia,2022,137525,34.96,230016,58.48

In [1]:
#Cambio il formato data
cittadinanza_2022['Anno'] = pd.to_datetime(cittadinanza_2022['Anno'], format='%Y')
cittadinanza_2022

NameError: name 'pd' is not defined

In [ ]:
#  Gestisci NaN 
coniugatienon_2022 = coniugatienon_2022.dropna()
coniugatienon_2022

In [ ]:
# Esporto in CSV
coniugatienon_2022.to_csv('coniugatienon_2022.csv', index=False, encoding='utf-8', na_rep=None)

In [ ]:
#Importiamo il database Nati per genitori coniugati o non coniugati 2023
coniugatienon_2023 = pd.read_csv(r'C:\Users\paster\Downloads\Nascite (17).csv')
coniugatienon_2023

In [ ]:
cols_to_drop = ['Genitori già coniugati - V.A.','Genitori già coniugati - %','Totale - V.A.','Note']
coniugatienon_2023 = coniugatienon_2023.drop(columns=cols_to_drop, errors='ignore') 
coniugatienon_2023

In [ ]:
#  Gestisci NaN 
coniugatienon_2023 = coniugatienon_2023.dropna()
coniugatienon_2023

In [ ]:
#Cambio il formato data
coniugatienon_2023['Anno'] = pd.to_datetime(coniugatienon['Anno'], format='%Y')
coniugatienon_2023

In [79]:
# Esporto in CSV
coniugatienon_2023.to_csv('coniugatienon_2023.csv', index=False, encoding='utf-8', na_rep=None)

NameError: name 'coniugatienon_2023' is not defined

In [97]:
#Importiamo il database dei Nomi Femminili più diffusi per Regione
I_S2021= pd.read_csv(r'C:\Users\paster\Downloads\Nascite (21).csv')
I_S2021

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti,Note
0,Piemonte,2021,13711,12989,26700,2464,2496,4960,NaN
1,Valle d'Aosta/Vallée d'Aoste,2021,396,348,744,53,53,106,NaN
2,Liguria,2021,4412,4144,8556,911,876,1787,NaN
3,Lombardia,2021,35332,33586,68918,7270,6942,14212,NaN
4,Trentino-Alto Adige/Südtirol,2021,4818,4545,9363,651,618,1269,NaN
5,Provincia Autonoma di Bolzano,2021,2664,2509,5173,360,320,680,NaN
6,Provincia Autonoma di Trento,2021,2154,2036,4190,291,298,589,NaN
7,Veneto,2021,16766,16033,32799,3291,3238,6529,NaN
8,Friuli-Venezia Giulia,2021,3710,3559,7269,683,648,1331,NaN
9,Emilia-Romagna,2021,15442,14394,29836,3681,3487,7168,NaN
10,Toscana,2021,11532,11060,22592,2138,2057,4195,NaN
11,Umbria,2021,2652,2586,5238,433,465,898,NaN
12,Marche,2021,4655,4567,9222,716,681,1397,NaN
13,Lazio,2021,19077,18160,37237,2772,2533,5305,NaN
14,Abruzzo,2021,4201,4089,8290,407,358,765,NaN
15,Molise,2021,859,826,1685,51,45,96,NaN
16,Campania,2021,22314,21089,43403,1075,989,2064,NaN
17,Puglia,2021,13601,12780,26381,716,702,1418,NaN
18,Basilicata,2021,1711,1619,3330,116,96,212,NaN
19,Calabria,2021,6735,6484,13219,451,396,847,NaN
20,Sicilia,2021,19090,18145,37235,989,1018,2007,NaN
21,Sardegna,2021,4175,4057,8232,173,187,360,NaN
22,Italia,2021,205189,195060,400249,29041,27885,56926,NaN

In [98]:
cols_to_drop = ['Note']
I_S2021 = I_S2021.drop(columns=cols_to_drop, errors='ignore') 
I_S2021

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2021,13711,12989,26700,2464,2496,4960
1,Valle d'Aosta/Vallée d'Aoste,2021,396,348,744,53,53,106
2,Liguria,2021,4412,4144,8556,911,876,1787
3,Lombardia,2021,35332,33586,68918,7270,6942,14212
4,Trentino-Alto Adige/Südtirol,2021,4818,4545,9363,651,618,1269
5,Provincia Autonoma di Bolzano,2021,2664,2509,5173,360,320,680
6,Provincia Autonoma di Trento,2021,2154,2036,4190,291,298,589
7,Veneto,2021,16766,16033,32799,3291,3238,6529
8,Friuli-Venezia Giulia,2021,3710,3559,7269,683,648,1331
9,Emilia-Romagna,2021,15442,14394,29836,3681,3487,7168
10,Toscana,2021,11532,11060,22592,2138,2057,4195
11,Umbria,2021,2652,2586,5238,433,465,898
12,Marche,2021,4655,4567,9222,716,681,1397
13,Lazio,2021,19077,18160,37237,2772,2533,5305
14,Abruzzo,2021,4201,4089,8290,407,358,765
15,Molise,2021,859,826,1685,51,45,96
16,Campania,2021,22314,21089,43403,1075,989,2064
17,Puglia,2021,13601,12780,26381,716,702,1418
18,Basilicata,2021,1711,1619,3330,116,96,212
19,Calabria,2021,6735,6484,13219,451,396,847
20,Sicilia,2021,19090,18145,37235,989,1018,2007
21,Sardegna,2021,4175,4057,8232,173,187,360
22,Italia,2021,205189,195060,400249,29041,27885,56926

In [99]:
#Cambio il formato data
I_S2021['Anno'] = pd.to_datetime(I_S2021['Anno'], format='%Y')
I_S2021

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2021-01-01,13711,12989,26700,2464,2496,4960
1,Valle d'Aosta/Vallée d'Aoste,2021-01-01,396,348,744,53,53,106
2,Liguria,2021-01-01,4412,4144,8556,911,876,1787
3,Lombardia,2021-01-01,35332,33586,68918,7270,6942,14212
4,Trentino-Alto Adige/Südtirol,2021-01-01,4818,4545,9363,651,618,1269
5,Provincia Autonoma di Bolzano,2021-01-01,2664,2509,5173,360,320,680
6,Provincia Autonoma di Trento,2021-01-01,2154,2036,4190,291,298,589
7,Veneto,2021-01-01,16766,16033,32799,3291,3238,6529
8,Friuli-Venezia Giulia,2021-01-01,3710,3559,7269,683,648,1331
9,Emilia-Romagna,2021-01-01,15442,14394,29836,3681,3487,7168
10,Toscana,2021-01-01,11532,11060,22592,2138,2057,4195
11,Umbria,2021-01-01,2652,2586,5238,433,465,898
12,Marche,2021-01-01,4655,4567,9222,716,681,1397
13,Lazio,2021-01-01,19077,18160,37237,2772,2533,5305
14,Abruzzo,2021-01-01,4201,4089,8290,407,358,765
15,Molise,2021-01-01,859,826,1685,51,45,96
16,Campania,2021-01-01,22314,21089,43403,1075,989,2064
17,Puglia,2021-01-01,13601,12780,26381,716,702,1418
18,Basilicata,2021-01-01,1711,1619,3330,116,96,212
19,Calabria,2021-01-01,6735,6484,13219,451,396,847
20,Sicilia,2021-01-01,19090,18145,37235,989,1018,2007
21,Sardegna,2021-01-01,4175,4057,8232,173,187,360
22,Italia,2021-01-01,205189,195060,400249,29041,27885,56926

In [100]:
#  Gestisci NaN 
I_S2021 = I_S2021.dropna()
I_S2021

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2021-01-01,13711,12989,26700,2464,2496,4960
1,Valle d'Aosta/Vallée d'Aoste,2021-01-01,396,348,744,53,53,106
2,Liguria,2021-01-01,4412,4144,8556,911,876,1787
3,Lombardia,2021-01-01,35332,33586,68918,7270,6942,14212
4,Trentino-Alto Adige/Südtirol,2021-01-01,4818,4545,9363,651,618,1269
5,Provincia Autonoma di Bolzano,2021-01-01,2664,2509,5173,360,320,680
6,Provincia Autonoma di Trento,2021-01-01,2154,2036,4190,291,298,589
7,Veneto,2021-01-01,16766,16033,32799,3291,3238,6529
8,Friuli-Venezia Giulia,2021-01-01,3710,3559,7269,683,648,1331
9,Emilia-Romagna,2021-01-01,15442,14394,29836,3681,3487,7168
10,Toscana,2021-01-01,11532,11060,22592,2138,2057,4195
11,Umbria,2021-01-01,2652,2586,5238,433,465,898
12,Marche,2021-01-01,4655,4567,9222,716,681,1397
13,Lazio,2021-01-01,19077,18160,37237,2772,2533,5305
14,Abruzzo,2021-01-01,4201,4089,8290,407,358,765
15,Molise,2021-01-01,859,826,1685,51,45,96
16,Campania,2021-01-01,22314,21089,43403,1075,989,2064
17,Puglia,2021-01-01,13601,12780,26381,716,702,1418
18,Basilicata,2021-01-01,1711,1619,3330,116,96,212
19,Calabria,2021-01-01,6735,6484,13219,451,396,847
20,Sicilia,2021-01-01,19090,18145,37235,989,1018,2007
21,Sardegna,2021-01-01,4175,4057,8232,173,187,360
22,Italia,2021-01-01,205189,195060,400249,29041,27885,56926

In [101]:
# Esporto in CSV
I_S2021.to_csv('I_S2021.csv', index=False, encoding='utf-8', na_rep=None)

In [87]:
#Importiamo il database dei Nomi Femminili più diffusi per Regione
I_S2023= pd.read_csv(r'C:\Users\paster\Downloads\Nascite (19).csv')
I_S2023

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti,Note
0,Piemonte,2023,12915,12162,25077,2335,2142,4477,NaN
1,Valle d'Aosta/Vallée d'Aoste,2023,364,354,718,31,31,62,NaN
2,Liguria,2023,4323,4020,8343,850,795,1645,NaN
3,Lombardia,2023,33873,31786,65659,6622,6230,12852,NaN
4,Trentino-Alto Adige/Südtirol,2023,4403,4081,8484,560,526,1086,NaN
5,Provincia Autonoma di Bolzano,2023,2428,2267,4695,299,302,601,NaN
6,Provincia Autonoma di Trento,2023,1975,1814,3789,261,224,485,NaN
7,Veneto,2023,15615,14823,30438,2863,2799,5662,NaN
8,Friuli-Venezia Giulia,2023,3557,3425,6982,642,605,1247,NaN
9,Emilia-Romagna,2023,14748,13820,28568,3237,3009,6246,NaN
10,Toscana,2023,10721,10154,20875,1952,1827,3779,NaN
11,Umbria,2023,2447,2319,4766,354,326,680,NaN
12,Marche,2023,4505,4292,8797,650,605,1255,NaN
13,Lazio,2023,17633,16659,34292,2492,2372,4864,NaN
14,Abruzzo,2023,3955,3623,7578,383,376,759,NaN
15,Molise,2023,868,793,1661,41,55,96,NaN
16,Campania,2023,22009,20916,42925,1149,1126,2275,NaN
17,Puglia,2023,13121,12470,25591,696,680,1376,NaN
18,Basilicata,2023,1597,1526,3123,122,98,220,NaN
19,Calabria,2023,6793,6489,13282,445,342,787,NaN
20,Sicilia,2023,18182,17307,35489,887,911,1798,NaN
21,Sardegna,2023,3747,3495,7242,138,143,281,NaN
22,Italia,2023,195376,184514,379890,26449,24998,51447,NaN

In [88]:
cols_to_drop = ['Note']
I_S2023 = I_S2023.drop(columns=cols_to_drop, errors='ignore') 
I_S2023

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2023,12915,12162,25077,2335,2142,4477
1,Valle d'Aosta/Vallée d'Aoste,2023,364,354,718,31,31,62
2,Liguria,2023,4323,4020,8343,850,795,1645
3,Lombardia,2023,33873,31786,65659,6622,6230,12852
4,Trentino-Alto Adige/Südtirol,2023,4403,4081,8484,560,526,1086
5,Provincia Autonoma di Bolzano,2023,2428,2267,4695,299,302,601
6,Provincia Autonoma di Trento,2023,1975,1814,3789,261,224,485
7,Veneto,2023,15615,14823,30438,2863,2799,5662
8,Friuli-Venezia Giulia,2023,3557,3425,6982,642,605,1247
9,Emilia-Romagna,2023,14748,13820,28568,3237,3009,6246
10,Toscana,2023,10721,10154,20875,1952,1827,3779
11,Umbria,2023,2447,2319,4766,354,326,680
12,Marche,2023,4505,4292,8797,650,605,1255
13,Lazio,2023,17633,16659,34292,2492,2372,4864
14,Abruzzo,2023,3955,3623,7578,383,376,759
15,Molise,2023,868,793,1661,41,55,96
16,Campania,2023,22009,20916,42925,1149,1126,2275
17,Puglia,2023,13121,12470,25591,696,680,1376
18,Basilicata,2023,1597,1526,3123,122,98,220
19,Calabria,2023,6793,6489,13282,445,342,787
20,Sicilia,2023,18182,17307,35489,887,911,1798
21,Sardegna,2023,3747,3495,7242,138,143,281
22,Italia,2023,195376,184514,379890,26449,24998,51447

In [89]:
#  Gestisci NaN 
I_S2023 = I_S2023.dropna()
I_S2023

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2023,12915,12162,25077,2335,2142,4477
1,Valle d'Aosta/Vallée d'Aoste,2023,364,354,718,31,31,62
2,Liguria,2023,4323,4020,8343,850,795,1645
3,Lombardia,2023,33873,31786,65659,6622,6230,12852
4,Trentino-Alto Adige/Südtirol,2023,4403,4081,8484,560,526,1086
5,Provincia Autonoma di Bolzano,2023,2428,2267,4695,299,302,601
6,Provincia Autonoma di Trento,2023,1975,1814,3789,261,224,485
7,Veneto,2023,15615,14823,30438,2863,2799,5662
8,Friuli-Venezia Giulia,2023,3557,3425,6982,642,605,1247
9,Emilia-Romagna,2023,14748,13820,28568,3237,3009,6246
10,Toscana,2023,10721,10154,20875,1952,1827,3779
11,Umbria,2023,2447,2319,4766,354,326,680
12,Marche,2023,4505,4292,8797,650,605,1255
13,Lazio,2023,17633,16659,34292,2492,2372,4864
14,Abruzzo,2023,3955,3623,7578,383,376,759
15,Molise,2023,868,793,1661,41,55,96
16,Campania,2023,22009,20916,42925,1149,1126,2275
17,Puglia,2023,13121,12470,25591,696,680,1376
18,Basilicata,2023,1597,1526,3123,122,98,220
19,Calabria,2023,6793,6489,13282,445,342,787
20,Sicilia,2023,18182,17307,35489,887,911,1798
21,Sardegna,2023,3747,3495,7242,138,143,281
22,Italia,2023,195376,184514,379890,26449,24998,51447

In [90]:
#Cambio il formato data
I_S2023['Anno'] = pd.to_datetime(I_S2023['Anno'], format='%Y')
I_S2023

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2023-01-01,12915,12162,25077,2335,2142,4477
1,Valle d'Aosta/Vallée d'Aoste,2023-01-01,364,354,718,31,31,62
2,Liguria,2023-01-01,4323,4020,8343,850,795,1645
3,Lombardia,2023-01-01,33873,31786,65659,6622,6230,12852
4,Trentino-Alto Adige/Südtirol,2023-01-01,4403,4081,8484,560,526,1086
5,Provincia Autonoma di Bolzano,2023-01-01,2428,2267,4695,299,302,601
6,Provincia Autonoma di Trento,2023-01-01,1975,1814,3789,261,224,485
7,Veneto,2023-01-01,15615,14823,30438,2863,2799,5662
8,Friuli-Venezia Giulia,2023-01-01,3557,3425,6982,642,605,1247
9,Emilia-Romagna,2023-01-01,14748,13820,28568,3237,3009,6246
10,Toscana,2023-01-01,10721,10154,20875,1952,1827,3779
11,Umbria,2023-01-01,2447,2319,4766,354,326,680
12,Marche,2023-01-01,4505,4292,8797,650,605,1255
13,Lazio,2023-01-01,17633,16659,34292,2492,2372,4864
14,Abruzzo,2023-01-01,3955,3623,7578,383,376,759
15,Molise,2023-01-01,868,793,1661,41,55,96
16,Campania,2023-01-01,22009,20916,42925,1149,1126,2275
17,Puglia,2023-01-01,13121,12470,25591,696,680,1376
18,Basilicata,2023-01-01,1597,1526,3123,122,98,220
19,Calabria,2023-01-01,6793,6489,13282,445,342,787
20,Sicilia,2023-01-01,18182,17307,35489,887,911,1798
21,Sardegna,2023-01-01,3747,3495,7242,138,143,281
22,Italia,2023-01-01,195376,184514,379890,26449,24998,51447

In [91]:
# Esporto in CSV
I_S2023.to_csv('I_S2023.csv', index=False, encoding='utf-8', na_rep=None)

In [92]:
#Importiamo il database dei Nomi Femminili più diffusi per Regione
I_S2022= pd.read_csv(r'C:\Users\paster\Downloads\Nascite (20).csv')
I_S2022

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti,Note
0,Piemonte,2022,13264,12711,25975,2313,2253,4566,NaN
1,Valle d'Aosta/Vallée d'Aoste,2022,400,381,781,31,36,67,NaN
2,Liguria,2022,4402,4077,8479,875,794,1669,NaN
3,Lombardia,2022,34902,32580,67482,7022,6418,13440,NaN
4,Trentino-Alto Adige/Südtirol,2022,4593,4330,8923,628,611,1239,NaN
5,Provincia Autonoma di Bolzano,2022,2446,2466,4912,324,344,668,NaN
6,Provincia Autonoma di Trento,2022,2147,1864,4011,304,267,571,NaN
7,Veneto,2022,16353,15401,31754,3105,2895,6000,NaN
8,Friuli-Venezia Giulia,2022,3739,3538,7277,657,618,1275,NaN
9,Emilia-Romagna,2022,15121,14494,29615,3261,3184,6445,NaN
10,Toscana,2022,11099,10511,21610,1908,1829,3737,NaN
11,Umbria,2022,2523,2403,4926,384,389,773,NaN
12,Marche,2022,4511,4277,8788,616,609,1225,NaN
13,Lazio,2022,18559,17503,36062,2578,2445,5023,NaN
14,Abruzzo,2022,4185,3838,8023,408,326,734,NaN
15,Molise,2022,864,819,1683,43,49,92,NaN
16,Campania,2022,22835,21634,44469,1157,1040,2197,NaN
17,Puglia,2022,13643,12658,26301,711,677,1388,NaN
18,Basilicata,2022,1734,1487,3221,113,110,223,NaN
19,Calabria,2022,6936,6515,13451,388,389,777,NaN
20,Sicilia,2022,19161,17649,36810,973,919,1892,NaN
21,Sardegna,2022,4016,3687,7703,166,151,317,NaN
22,Italia,2022,202840,190493,393333,27337,25742,53079,NaN

In [93]:
cols_to_drop = ['Note']
I_S2022 = I_S2022.drop(columns=cols_to_drop, errors='ignore') 
I_S2022

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2022,13264,12711,25975,2313,2253,4566
1,Valle d'Aosta/Vallée d'Aoste,2022,400,381,781,31,36,67
2,Liguria,2022,4402,4077,8479,875,794,1669
3,Lombardia,2022,34902,32580,67482,7022,6418,13440
4,Trentino-Alto Adige/Südtirol,2022,4593,4330,8923,628,611,1239
5,Provincia Autonoma di Bolzano,2022,2446,2466,4912,324,344,668
6,Provincia Autonoma di Trento,2022,2147,1864,4011,304,267,571
7,Veneto,2022,16353,15401,31754,3105,2895,6000
8,Friuli-Venezia Giulia,2022,3739,3538,7277,657,618,1275
9,Emilia-Romagna,2022,15121,14494,29615,3261,3184,6445
10,Toscana,2022,11099,10511,21610,1908,1829,3737
11,Umbria,2022,2523,2403,4926,384,389,773
12,Marche,2022,4511,4277,8788,616,609,1225
13,Lazio,2022,18559,17503,36062,2578,2445,5023
14,Abruzzo,2022,4185,3838,8023,408,326,734
15,Molise,2022,864,819,1683,43,49,92
16,Campania,2022,22835,21634,44469,1157,1040,2197
17,Puglia,2022,13643,12658,26301,711,677,1388
18,Basilicata,2022,1734,1487,3221,113,110,223
19,Calabria,2022,6936,6515,13451,388,389,777
20,Sicilia,2022,19161,17649,36810,973,919,1892
21,Sardegna,2022,4016,3687,7703,166,151,317
22,Italia,2022,202840,190493,393333,27337,25742,53079

In [94]:
#Cambio il formato data
I_S2022['Anno'] = pd.to_datetime(I_S2022['Anno'], format='%Y')
I_S2022

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2022-01-01,13264,12711,25975,2313,2253,4566
1,Valle d'Aosta/Vallée d'Aoste,2022-01-01,400,381,781,31,36,67
2,Liguria,2022-01-01,4402,4077,8479,875,794,1669
3,Lombardia,2022-01-01,34902,32580,67482,7022,6418,13440
4,Trentino-Alto Adige/Südtirol,2022-01-01,4593,4330,8923,628,611,1239
5,Provincia Autonoma di Bolzano,2022-01-01,2446,2466,4912,324,344,668
6,Provincia Autonoma di Trento,2022-01-01,2147,1864,4011,304,267,571
7,Veneto,2022-01-01,16353,15401,31754,3105,2895,6000
8,Friuli-Venezia Giulia,2022-01-01,3739,3538,7277,657,618,1275
9,Emilia-Romagna,2022-01-01,15121,14494,29615,3261,3184,6445
10,Toscana,2022-01-01,11099,10511,21610,1908,1829,3737
11,Umbria,2022-01-01,2523,2403,4926,384,389,773
12,Marche,2022-01-01,4511,4277,8788,616,609,1225
13,Lazio,2022-01-01,18559,17503,36062,2578,2445,5023
14,Abruzzo,2022-01-01,4185,3838,8023,408,326,734
15,Molise,2022-01-01,864,819,1683,43,49,92
16,Campania,2022-01-01,22835,21634,44469,1157,1040,2197
17,Puglia,2022-01-01,13643,12658,26301,711,677,1388
18,Basilicata,2022-01-01,1734,1487,3221,113,110,223
19,Calabria,2022-01-01,6936,6515,13451,388,389,777
20,Sicilia,2022-01-01,19161,17649,36810,973,919,1892
21,Sardegna,2022-01-01,4016,3687,7703,166,151,317
22,Italia,2022-01-01,202840,190493,393333,27337,25742,53079

In [95]:
#  Gestisci NaN 
I_S2022 = I_S2022.dropna()
I_S2022

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2022-01-01,13264,12711,25975,2313,2253,4566
1,Valle d'Aosta/Vallée d'Aoste,2022-01-01,400,381,781,31,36,67
2,Liguria,2022-01-01,4402,4077,8479,875,794,1669
3,Lombardia,2022-01-01,34902,32580,67482,7022,6418,13440
4,Trentino-Alto Adige/Südtirol,2022-01-01,4593,4330,8923,628,611,1239
5,Provincia Autonoma di Bolzano,2022-01-01,2446,2466,4912,324,344,668
6,Provincia Autonoma di Trento,2022-01-01,2147,1864,4011,304,267,571
7,Veneto,2022-01-01,16353,15401,31754,3105,2895,6000
8,Friuli-Venezia Giulia,2022-01-01,3739,3538,7277,657,618,1275
9,Emilia-Romagna,2022-01-01,15121,14494,29615,3261,3184,6445
10,Toscana,2022-01-01,11099,10511,21610,1908,1829,3737
11,Umbria,2022-01-01,2523,2403,4926,384,389,773
12,Marche,2022-01-01,4511,4277,8788,616,609,1225
13,Lazio,2022-01-01,18559,17503,36062,2578,2445,5023
14,Abruzzo,2022-01-01,4185,3838,8023,408,326,734
15,Molise,2022-01-01,864,819,1683,43,49,92
16,Campania,2022-01-01,22835,21634,44469,1157,1040,2197
17,Puglia,2022-01-01,13643,12658,26301,711,677,1388
18,Basilicata,2022-01-01,1734,1487,3221,113,110,223
19,Calabria,2022-01-01,6936,6515,13451,388,389,777
20,Sicilia,2022-01-01,19161,17649,36810,973,919,1892
21,Sardegna,2022-01-01,4016,3687,7703,166,151,317
22,Italia,2022-01-01,202840,190493,393333,27337,25742,53079

In [96]:
# Esporto in CSV
I_S2022.to_csv('I_S2022.csv', index=False, encoding='utf-8', na_rep=None)

In [102]:
#Importiamo il database dei Nomi Femminili più diffusi per Regione
I_S2020= pd.read_csv(r'C:\Users\paster\Downloads\Nascite (22).csv')
I_S2020

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti,Note
0,Piemonte,2020,14009,13098,27107,2646,2570,5216,NaN
1,Valle d'Aosta/Vallée d'Aoste,2020,381,395,776,48,44,92,NaN
2,Liguria,2020,4454,4298,8752,959,935,1894,NaN
3,Lombardia,2020,35556,33679,69235,7875,7335,15210,NaN
4,Trentino-Alto Adige/Südtirol,2020,4744,4495,9239,697,658,1355,NaN
5,Provincia Autonoma di Bolzano,2020,2641,2550,5191,356,366,722,NaN
6,Provincia Autonoma di Trento,2020,2103,1945,4048,341,292,633,NaN
7,Veneto,2020,16967,15705,32672,3539,3209,6748,NaN
8,Friuli-Venezia Giulia,2020,3752,3682,7434,680,674,1354,NaN
9,Emilia-Romagna,2020,15338,14523,29861,3738,3574,7312,NaN
10,Toscana,2020,11573,10807,22380,2232,2097,4329,NaN
11,Umbria,2020,2730,2538,5268,474,434,908,NaN
12,Marche,2020,4897,4535,9432,752,700,1452,NaN
13,Lazio,2020,19402,18580,37982,2930,2837,5767,NaN
14,Abruzzo,2020,4231,4006,8237,402,371,773,NaN
15,Molise,2020,909,804,1713,62,54,116,NaN
16,Campania,2020,23170,21908,45078,1187,1162,2349,NaN
17,Puglia,2020,13726,12729,26455,781,691,1472,NaN
18,Basilicata,2020,1849,1674,3523,119,100,219,NaN
19,Calabria,2020,7100,6866,13966,444,439,883,NaN
20,Sicilia,2020,19327,18193,37520,1034,971,2005,NaN
21,Sardegna,2020,4316,3946,8262,169,169,338,NaN
22,Italia,2020,208431,196461,404892,30768,29024,59792,NaN

In [103]:
cols_to_drop = ['Note']
I_S2020 = I_S2020.drop(columns=cols_to_drop, errors='ignore') 
I_S2020

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2020,14009,13098,27107,2646,2570,5216
1,Valle d'Aosta/Vallée d'Aoste,2020,381,395,776,48,44,92
2,Liguria,2020,4454,4298,8752,959,935,1894
3,Lombardia,2020,35556,33679,69235,7875,7335,15210
4,Trentino-Alto Adige/Südtirol,2020,4744,4495,9239,697,658,1355
5,Provincia Autonoma di Bolzano,2020,2641,2550,5191,356,366,722
6,Provincia Autonoma di Trento,2020,2103,1945,4048,341,292,633
7,Veneto,2020,16967,15705,32672,3539,3209,6748
8,Friuli-Venezia Giulia,2020,3752,3682,7434,680,674,1354
9,Emilia-Romagna,2020,15338,14523,29861,3738,3574,7312
10,Toscana,2020,11573,10807,22380,2232,2097,4329
11,Umbria,2020,2730,2538,5268,474,434,908
12,Marche,2020,4897,4535,9432,752,700,1452
13,Lazio,2020,19402,18580,37982,2930,2837,5767
14,Abruzzo,2020,4231,4006,8237,402,371,773
15,Molise,2020,909,804,1713,62,54,116
16,Campania,2020,23170,21908,45078,1187,1162,2349
17,Puglia,2020,13726,12729,26455,781,691,1472
18,Basilicata,2020,1849,1674,3523,119,100,219
19,Calabria,2020,7100,6866,13966,444,439,883
20,Sicilia,2020,19327,18193,37520,1034,971,2005
21,Sardegna,2020,4316,3946,8262,169,169,338
22,Italia,2020,208431,196461,404892,30768,29024,59792

In [104]:
#  Gestisci NaN 
I_S2020 = I_S2020.dropna()
I_S2020

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2020,14009,13098,27107,2646,2570,5216
1,Valle d'Aosta/Vallée d'Aoste,2020,381,395,776,48,44,92
2,Liguria,2020,4454,4298,8752,959,935,1894
3,Lombardia,2020,35556,33679,69235,7875,7335,15210
4,Trentino-Alto Adige/Südtirol,2020,4744,4495,9239,697,658,1355
5,Provincia Autonoma di Bolzano,2020,2641,2550,5191,356,366,722
6,Provincia Autonoma di Trento,2020,2103,1945,4048,341,292,633
7,Veneto,2020,16967,15705,32672,3539,3209,6748
8,Friuli-Venezia Giulia,2020,3752,3682,7434,680,674,1354
9,Emilia-Romagna,2020,15338,14523,29861,3738,3574,7312
10,Toscana,2020,11573,10807,22380,2232,2097,4329
11,Umbria,2020,2730,2538,5268,474,434,908
12,Marche,2020,4897,4535,9432,752,700,1452
13,Lazio,2020,19402,18580,37982,2930,2837,5767
14,Abruzzo,2020,4231,4006,8237,402,371,773
15,Molise,2020,909,804,1713,62,54,116
16,Campania,2020,23170,21908,45078,1187,1162,2349
17,Puglia,2020,13726,12729,26455,781,691,1472
18,Basilicata,2020,1849,1674,3523,119,100,219
19,Calabria,2020,7100,6866,13966,444,439,883
20,Sicilia,2020,19327,18193,37520,1034,971,2005
21,Sardegna,2020,4316,3946,8262,169,169,338
22,Italia,2020,208431,196461,404892,30768,29024,59792

In [105]:
#Cambio il formato data
I_S2020['Anno'] = pd.to_datetime(I_S2020['Anno'], format='%Y')
I_S2020

,Regione,Anno,Maschi residenti,Femmine residenti,Totale residenti,Maschi stranieri residenti,Femmine straniere residenti,Totale stranieri residenti
0,Piemonte,2020-01-01,14009,13098,27107,2646,2570,5216
1,Valle d'Aosta/Vallée d'Aoste,2020-01-01,381,395,776,48,44,92
2,Liguria,2020-01-01,4454,4298,8752,959,935,1894
3,Lombardia,2020-01-01,35556,33679,69235,7875,7335,15210
4,Trentino-Alto Adige/Südtirol,2020-01-01,4744,4495,9239,697,658,1355
5,Provincia Autonoma di Bolzano,2020-01-01,2641,2550,5191,356,366,722
6,Provincia Autonoma di Trento,2020-01-01,2103,1945,4048,341,292,633
7,Veneto,2020-01-01,16967,15705,32672,3539,3209,6748
8,Friuli-Venezia Giulia,2020-01-01,3752,3682,7434,680,674,1354
9,Emilia-Romagna,2020-01-01,15338,14523,29861,3738,3574,7312
10,Toscana,2020-01-01,11573,10807,22380,2232,2097,4329
11,Umbria,2020-01-01,2730,2538,5268,474,434,908
12,Marche,2020-01-01,4897,4535,9432,752,700,1452
13,Lazio,2020-01-01,19402,18580,37982,2930,2837,5767
14,Abruzzo,2020-01-01,4231,4006,8237,402,371,773
15,Molise,2020-01-01,909,804,1713,62,54,116
16,Campania,2020-01-01,23170,21908,45078,1187,1162,2349
17,Puglia,2020-01-01,13726,12729,26455,781,691,1472
18,Basilicata,2020-01-01,1849,1674,3523,119,100,219
19,Calabria,2020-01-01,7100,6866,13966,444,439,883
20,Sicilia,2020-01-01,19327,18193,37520,1034,971,2005
21,Sardegna,2020-01-01,4316,3946,8262,169,169,338
22,Italia,2020-01-01,208431,196461,404892,30768,29024,59792

In [106]:
# Esporto in CSV
I_S2020.to_csv('I_S2020.csv', index=False, encoding='utf-8', na_rep=None)